-- upgrade_key: 20260729-014-cashier-v3-entitlement-completion-persistence-v1
-- MySQL 5.6.51 compatible. Run 01 first and 03 afterwards.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_entitlement_completion_receipt` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `receipt_id` varchar(44) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `plan_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `workspace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `state_context_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `occurred_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `settled_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recorded_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `line_count` int(10) unsigned NOT NULL DEFAULT '0',
  `service_quantity` bigint(20) unsigned NOT NULL DEFAULT '0',
  `actual_entitlement_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumption_performance_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `labor_performance_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `result_json` mediumtext NOT NULL,
  `created_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `updated_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `completed_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_receipt_id` (`receipt_id`),
  UNIQUE KEY `uk_tenant_checkout_request` (`tenant_id`,`checkout_request_id`),
  UNIQUE KEY `uk_tenant_command_idem` (`tenant_id`,`command_idempotency_key`),
  KEY `idx_scope_date_status` (`tenant_id`,`store_id`,`business_date`,`status`,`id`),
  KEY `idx_member_time` (`tenant_id`,`member_id`,`occurred_at`,`id`),
  KEY `idx_workspace` (`tenant_id`,`workspace_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 entitlement completion idempotent receipt';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_entitlement_writeoff_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `writeoff_id` varchar(44) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_path_snapshot` varchar(512) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `occurred_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `settled_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recorded_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `document_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_document_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `entitlement_instance_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `entitlement_instance_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_kind` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `is_gift` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `gift_source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `gift_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `gift_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `holder_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `origin_order_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `source_code_snapshot` varchar(128) NOT NULL DEFAULT '',
  `source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `project_category_id_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_category_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `source_version_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `detail_version_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity` bigint(20) unsigned NOT NULL DEFAULT '0',
  `actual_entitlement_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `purchase_amount_cents_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `total_purchase_times_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumed_times_before_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `amount_calculation_version_snapshot` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `service_object` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `is_experience` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `primary_craftsman_staff_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `craftsmen_snapshot_json` mediumtext NOT NULL,
  `occupation_snapshot_json` mediumtext NOT NULL,
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_writeoff_id` (`writeoff_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_tenant_checkout_line` (`tenant_id`,`checkout_request_id`,`source_line_id`),
  KEY `idx_scope_date_status` (`tenant_id`,`store_id`,`business_date`,`status`,`id`),
  KEY `idx_member_project_time` (`tenant_id`,`member_id`,`project_id`,`occurred_at`,`id`),
  KEY `idx_entitlement_source` (`tenant_id`,`holder_id`,`source_detail_id`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable entitlement writeoff line facts';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_entitlement_service_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `service_fact_id` varchar(44) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_path_snapshot` varchar(512) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `occurred_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `settled_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recorded_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `document_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_document_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `project_category_id_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_category_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `quantity` bigint(20) unsigned NOT NULL DEFAULT '0',
  `service_object` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `is_experience` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `primary_craftsman_staff_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `craftsmen_snapshot_json` mediumtext NOT NULL,
  `service_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_fact_id` (`service_fact_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_tenant_checkout_line` (`tenant_id`,`checkout_request_id`,`source_line_id`),
  KEY `idx_scope_date_status` (`tenant_id`,`store_id`,`business_date`,`service_status`,`id`),
  KEY `idx_member_project_time` (`tenant_id`,`member_id`,`project_id`,`occurred_at`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable completed entitlement service line facts';

SELECT 'APPLY_OK' AS apply_result;
