-- upgrade_key: 20260805-003-inventory-v3-request-termination-transfer-reversal
SET NAMES utf8mb4;

SET @table_count := (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('eb_inventory_stock_request_lifecycle_operation','eb_inventory_cross_transfer_reversal_operation','eb_inventory_stock_request_fulfillment_reversal'));
SET @bad_request_operation := (SELECT COUNT(*) FROM eb_inventory_stock_request_lifecycle_operation WHERE request_document_id=0 OR idempotency_key='' OR request_fingerprint='' OR operation_type NOT IN ('CANCEL','TERMINATE') OR previous_status NOT IN ('APPLIED','PARTIAL') OR next_status NOT IN ('CANCELLED','TERMINATED') OR reason='' OR occurred_at=0 OR recorded_at<occurred_at);
SET @bad_transfer_operation := (SELECT COUNT(*) FROM eb_inventory_cross_transfer_reversal_operation WHERE transfer_document_id=0 OR idempotency_key='' OR request_fingerprint='' OR previous_status NOT IN ('DISPATCHED','RECEIVED') OR reason='' OR occurred_at=0 OR recorded_at<occurred_at);
SET @bad_fulfillment_reversal := (SELECT COUNT(*) FROM eb_inventory_stock_request_fulfillment_reversal r LEFT JOIN eb_inventory_stock_request_fulfillment f ON f.id=r.reversal_of WHERE r.request_document_id=0 OR r.request_line_id=0 OR r.reversal_of=0 OR r.transfer_reversal_operation_id=0 OR r.reversed_quantity_units=0 OR f.id IS NULL OR f.request_document_id<>r.request_document_id OR f.request_line_id<>r.request_line_id OR f.fulfilled_quantity_units<>r.reversed_quantity_units);
SET @bad_movement_reversal := (SELECT COUNT(*) FROM eb_inventory_batch_movement_fact r LEFT JOIN eb_inventory_batch_movement_fact o ON o.id=r.reversal_of WHERE r.source_type IN ('cross_transfer_in_reversal','cross_transfer_out_reversal') AND (r.reversal_of=0 OR o.id IS NULL OR r.stock_id<>o.stock_id OR r.batch_id<>o.batch_id OR r.direction<>-o.direction OR r.quantity_units<>o.quantity_units OR r.unit_cost_cents<>o.unit_cost_cents OR r.cost_amount_cents<>o.cost_amount_cents));
SELECT IF(@table_count=3 AND @bad_request_operation=0 AND @bad_transfer_operation=0 AND @bad_fulfillment_reversal=0 AND @bad_movement_reversal=0,'POSTCHECK_OK','POSTCHECK_FAILED') AS postcheck_result,
       @table_count AS table_count,@bad_request_operation AS bad_request_operation,@bad_transfer_operation AS bad_transfer_operation,@bad_fulfillment_reversal AS bad_fulfillment_reversal,@bad_movement_reversal AS bad_movement_reversal;

