-- upgrade_key: 20260729-012-cashier-v3-payment-collection-authority-v1
-- MySQL 5.6.51 compatible. Run 01 before and 03 after this script.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_payment_collection_batch` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `batch_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `contract_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_path_snapshot` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '0 means guest',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `sales_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_no_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_request_version` bigint(20) unsigned NOT NULL,
  `checkout_prepare_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_authority_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_aggregate_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `collection_count` int(10) unsigned NOT NULL DEFAULT '0',
  `collected_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cash_performance_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `receivable_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_document_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `batch_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `batch_version` bigint(20) unsigned NOT NULL,
  `batch_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reversal_of_batch_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `reversal_reason_snapshot` varchar(255) NOT NULL DEFAULT '',
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_batch_id` (`batch_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_tenant_checkout` (`tenant_id`,`checkout_request_id`),
  UNIQUE KEY `uk_tenant_order` (`tenant_id`,`sales_order_id`),
  KEY `idx_scope_date_status` (`tenant_id`,`store_id`,`business_date`,`batch_status`,`id`),
  KEY `idx_scope_settled` (`tenant_id`,`store_id`,`settled_at`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of_batch_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 authoritative payment collection set';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_payment_collection` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `collection_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `collection_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `contract_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `batch_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_path_snapshot` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '0 means guest',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `sales_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_no_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_request_version` bigint(20) unsigned NOT NULL,
  `checkout_payment_draft_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_payment_authority_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_payment_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_line_no` int(10) unsigned NOT NULL,
  `checkout_payment_sort_no` int(10) unsigned NOT NULL,
  `payment_method` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_method_name_snapshot` varchar(32) NOT NULL DEFAULT '',
  `amount_cents` bigint(20) unsigned NOT NULL,
  `cash_performance_amount_cents` bigint(20) unsigned NOT NULL,
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_business_time_snapshot` bigint(20) unsigned NOT NULL,
  `payment_recorded_at_snapshot` bigint(20) unsigned NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_document_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `external_transaction_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `remark_snapshot` varchar(255) NOT NULL DEFAULT '',
  `collection_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `collection_version` bigint(20) unsigned NOT NULL,
  `collection_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reversal_of_collection_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `reversal_reason_snapshot` varchar(255) NOT NULL DEFAULT '',
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collection_id` (`collection_id`),
  UNIQUE KEY `uk_tenant_collection_no` (`tenant_id`,`collection_no`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_checkout_payment_draft` (`tenant_id`,`checkout_request_id`,`checkout_payment_draft_id`),
  UNIQUE KEY `uk_batch_line_no` (`tenant_id`,`batch_id`,`payment_line_no`),
  KEY `idx_batch` (`tenant_id`,`batch_id`,`payment_line_no`,`id`),
  KEY `idx_scope_date_method` (`tenant_id`,`store_id`,`business_date`,`payment_method`,`collection_status`,`id`),
  KEY `idx_scope_settled` (`tenant_id`,`store_id`,`settled_at`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_sales_order` (`tenant_id`,`sales_order_id`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`),
  KEY `idx_external_reference` (`tenant_id`,`payment_method`,`external_transaction_no_snapshot`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of_collection_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable bookkeeping payment collections';

SELECT 'APPLY_OK' AS apply_result;
