<?php

/**
 * Explicit local-only active-customer baseline probe.
 *
 * Run this file against a detached baseline checkout with
 * MOHE_ACTIVE_BASELINE_MODE=legacy, then against the current checkout with
 * MOHE_ACTIVE_BASELINE_MODE=reader. It outputs aggregates only: no member,
 * store-name, order or credential data is printed. In legacy mode it does
 * retain the aggregate SQL generated by the historical employee active-
 * customer query, because that SQL is the evidence required to distinguish
 * a row count from a distinct-member count.
 */
if (getenv('MOHE_ACTIVE_BASELINE_CONFIRM') !== 'LOCAL_READ_ONLY') {
    exit("Explicit local read-only opt-in required\n");
}

$mode = (string)getenv('MOHE_ACTIVE_BASELINE_MODE');
if (!in_array($mode, ['legacy', 'reader'], true)) exit("Baseline mode must be legacy or reader\n");

$storeText = trim((string)getenv('MOHE_ACTIVE_BASELINE_STORE_IDS'));
$dateText = trim((string)getenv('MOHE_ACTIVE_BASELINE_RANGE'));
if (!preg_match('/^\d+(?:,\d+)+$/D', $storeText)
    || !preg_match('/^\d{4}-\d{2}-\d{2},\d{4}-\d{2}-\d{2}$/D', $dateText)) {
    exit("Exactly two or more stores and an explicit date range are required\n");
}
$stores = array_values(array_unique(array_map('intval', explode(',', $storeText))));
if (count($stores) < 2 || min($stores) <= 0) exit("At least two positive store ids are required\n");
list($start, $end) = explode(',', $dateText, 2);
if ($start > $end) exit("Invalid date range\n");

require getcwd() . '/vendor/autoload.php';
$app = new think\App();
$app->initialize();
$database = (array)config('database.connections.' . config('database.default'));
if (($database['hostname'] ?? '') !== 'mysql') exit("Target host mismatch\n");
$pdo = new PDO(
    'mysql:host=' . $database['hostname'] . ';port=' . $database['hostport'] . ';dbname=' . $database['database'] . ';charset=utf8mb4',
    $database['username'], $database['password'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_EMULATE_PREPARES => false]
);
$identity = $pdo->query('SELECT @@server_uuid uuid,DATABASE() db')->fetch(PDO::FETCH_ASSOC);
if (!$identity || $identity['uuid'] !== getenv('MOHE_ACTIVE_BASELINE_EXPECT_UUID')
    || $identity['db'] !== getenv('MOHE_ACTIVE_BASELINE_EXPECT_DB')) {
    exit("Target mismatch\n");
}

$fingerprint = static function () use ($stores, $start, $end): array {
    $service = think\facade\Db::name('cashier_v3_entitlement_service_fact')->alias('s')
        ->where('s.tenant_id', '0')->whereIn('s.store_id', $stores)
        ->whereBetween('s.business_date', [$start, $end])->where('s.service_status', 'completed')->where('s.member_id', '>', 0);
    (new app\services\report\StoreReportNormalDataScopeServices())->excludeVoidedSalesOrderServices($service, 's');
    $serviceRow = $service->fieldRaw("COUNT(*) row_count,COALESCE(MAX(s.id),0) max_id,COALESCE(SUM(CRC32(CONCAT_WS('|',s.id,s.store_id,s.business_date,s.member_id,s.source_line_id))),0) checksum")->find() ?: [];
    $voidRow = think\facade\Db::name('cashier_v3_order_lifecycle_operation')->alias('o')
        ->where('o.tenant_id', '0')->whereIn('o.store_id', $stores)
        ->whereBetween('o.business_date', [$start, $end])->where('o.source_type', 'sales')
        ->where('o.operation_type', 'void')->where('o.status', 'succeeded')
        ->fieldRaw("COUNT(*) row_count,COALESCE(MAX(o.id),0) max_id,COALESCE(SUM(CRC32(CONCAT_WS('|',o.id,o.source_order_id,o.business_date))),0) checksum")->find() ?: [];
    return [
        'eligible_service_rows' => (int)($serviceRow['row_count'] ?? 0),
        'eligible_service_max_id' => (int)($serviceRow['max_id'] ?? 0),
        'eligible_service_checksum' => (string)($serviceRow['checksum'] ?? '0'),
        'succeeded_void_rows' => (int)($voidRow['row_count'] ?? 0),
        'succeeded_void_max_id' => (int)($voidRow['max_id'] ?? 0),
        'succeeded_void_checksum' => (string)($voidRow['checksum'] ?? '0'),
    ];
};
$before = $fingerprint();

$scopeSets = [];
foreach ($stores as $storeId) $scopeSets[] = [(int)$storeId];
$scopeSets[] = $stores;
$rows = [];
foreach ($scopeSets as $scope) {
    $key = count($scope) === 1 ? 'store:' . $scope[0] : 'combined';
    if ($mode === 'reader') {
        $value = (new app\services\query\metric\RegisteredMetricReadServices())->summary(
            'customer_active', '0', $scope, ['start' => $start, 'end' => $end]
        );
        $rows[] = ['scope' => $key, 'store_ids' => $scope, 'reader_value' => (int)$value];
        continue;
    }

    $legacyRow = ['scope' => $key, 'store_ids' => $scope];
    try {
        $report = (new app\services\report\StoreUnifiedReportServices())->query($scope, [
            'report' => 'customers', 'start_date' => $start, 'end_date' => $end,
            'customer_segment' => 'active', '_internal_all' => true, '_report_scope' => ['mode' => 'all'],
        ]);
        $legacyRow['unified_report_value'] = (int)($report['total'] ?? 0);
    } catch (Throwable $exception) {
        $legacyRow['unified_report_status'] = 'LEGACY_PATH_UNAVAILABLE';
    }
    try {
        $employee = (new app\services\report\EmployeeDashboardServices())->dashboard($scope, ['start' => $start, 'end' => $end]);
        $employeeCards = array_column((array)($employee['performance']['cards'] ?? []), null, 'key');
        $legacyRow['employee_dashboard_value'] = (int)($employeeCards['active_customers']['value'] ?? 0);
        $employeeFacts = think\facade\Db::name('cashier_v3_entitlement_service_fact')->alias('sv')
            ->whereIn('sv.store_id', $scope)->whereBetween('sv.business_date', [$start, $end])
            ->where('sv.service_status', 'completed');
        (new app\services\report\StoreReportNormalDataScopeServices())->excludeVoidedSalesOrderServices($employeeFacts, 'sv');
        $memberFacts = (clone $employeeFacts)->where('sv.member_id', '>', 0);
        $legacyRow['employee_service_row_count'] = (int)(clone $memberFacts)->count();
        $distinctRow = (clone $memberFacts)->fieldRaw('COUNT(DISTINCT sv.member_id) AS metric_value')->find() ?: [];
        $legacyRow['employee_distinct_member_count'] = (int)($distinctRow['metric_value'] ?? 0);
        $legacyRow['employee_distinct_count_value'] = (int)(clone $memberFacts)->distinct(true)->count('sv.member_id');
        $legacyRow['employee_distinct_count_sql'] = (string)(clone $memberFacts)->distinct(true)->fetchSql(true)->count('sv.member_id');
    } catch (Throwable $exception) {
        $legacyRow['employee_dashboard_status'] = 'LEGACY_PATH_UNAVAILABLE';
    }
    try {
        $mobileClass = new ReflectionClass(app\services\mobile\warehouse\MobileWarehouseServices::class);
        $mobile = $mobileClass->newInstanceWithoutConstructor();
        $dictionary = $mobileClass->getProperty('dictionary');
        $dictionary->setAccessible(true);
        $dictionary->setValue($mobile, new app\services\metric\MetricDictionaryServices());
        $projection = $mobile->dashboardProjection($scope, [
            'periodMode' => 'custom', 'startDate' => $start, 'endDate' => $end, 'includeTrend' => false,
        ]);
        $mobileCards = array_column((array)($projection['summaryMetrics'] ?? []), null, 'code');
        $legacyRow['mobile_warehouse_value'] = (int)($mobileCards['visit_customer']['value'] ?? 0);
    } catch (Throwable $exception) {
        $legacyRow['mobile_warehouse_status'] = 'LEGACY_PATH_UNAVAILABLE';
    }
    $rows[] = $legacyRow;
}
$after = $fingerprint();
$hasUnavailableLegacy = false;
if ($mode === 'legacy') foreach ($rows as $row) {
    foreach (['unified_report_status', 'employee_dashboard_status', 'mobile_warehouse_status'] as $statusKey) {
        if (isset($row[$statusKey])) $hasUnavailableLegacy = true;
    }
}
echo json_encode([
    'result' => $before !== $after ? 'DATA_WATERMARK_CHANGED' : ($hasUnavailableLegacy ? 'PARTIAL_LEGACY_PATH_UNAVAILABLE' : 'PASS'),
    'mode' => $mode,
    'code_commit' => (string)getenv('MOHE_ACTIVE_BASELINE_CODE_COMMIT'),
    'range' => ['start' => $start, 'end' => $end],
    'store_count' => count($stores),
    'fingerprint_before' => $before,
    'fingerprint_after' => $after,
    'rows' => $rows,
    'business_records_modified' => false,
], JSON_UNESCAPED_UNICODE) . "\n";
