<?php
// Shared synthetic harness for gateway-management tests. It deliberately
// drives the only supported natural-language contract, never a legacy parser.
require_once __DIR__.'/fixture-autoload.php';
use app\services\ai\AiGatewayServices;
use app\services\ai\config\AiConfigStore;
use app\services\ai\config\AiPrivateStorage;
use app\services\ai\execution\AiRunStore;
use app\services\query\metric\MetricReadViewStore;
use app\services\query\metric\GroupPerformanceMetricReadServices;
function r6hCheck($ok,$label){if(!$ok)throw new RuntimeException('FAIL '.$label);}
class R6Facts {private $day='2026-09-01';public function __call($name,$args){if($name==='whereExists')$args[0]($this);if($name==='whereBetween')$this->day=$args[1][0];return $this;}public function find(){return ['amount_cents'=>'12345','gross_cents'=>'12345','refund_cents'=>'0'];}public function column(){return [1=>'一号门店',2=>'二号门店'];}public function toArray(){return [['store_id'=>'1','business_date'=>$this->day,'amount_cents'=>'12345','entity_id'=>'101','entity_name'=>'合成会员','metric_value'=>'12345']];}}
class R6GatewayHarness {
 public $db,$private,$gateway,$auth,$context,$temp,$boot,$models=0,$queries=0,$sequence=0,$semanticIntent=null,$semanticIntentByRepair=[],$understandingOverride=null,$bindingVerificationOverride=null,$bindingVerificationSequence=[],$bindingReviewKind=null,$modelInputs=[];
 public function __construct($rounds=3,$authorizedStores=[1],$terminal='store'){
  $GLOBALS['r5_rounds']=$rounds;$this->db=new PDO('sqlite::memory:');foreach(['CREATE TABLE mohe_ai_mutex(instance_id TEXT PRIMARY KEY,quarantined_slots INTEGER NOT NULL DEFAULT 0)','CREATE TABLE mohe_ai_receipt(instance_id TEXT,receipt_key TEXT,request_hash TEXT,window_id TEXT,run_id TEXT,reason TEXT,expires_at INTEGER,PRIMARY KEY(instance_id,receipt_key))','CREATE TABLE mohe_ai_attempt(instance_id TEXT,run_id TEXT,attempt_code TEXT,kind TEXT,target_code TEXT,payload_hash TEXT,state TEXT,input_tokens INTEGER,output_tokens INTEGER,created_at INTEGER,expires_at INTEGER,PRIMARY KEY(instance_id,run_id,attempt_code))','CREATE TABLE mohe_ai_run(instance_id TEXT,run_id TEXT,account_id INTEGER,terminal TEXT,conversation_id TEXT,window_id TEXT,generation INTEGER,status TEXT,reason TEXT,progress_code TEXT,clarification_ref TEXT,version INTEGER,created_at INTEGER,expires_at INTEGER,deadline_at INTEGER,last_clock_at INTEGER,remaining_ms INTEGER,pause_at INTEGER,clarification_count INTEGER,slot_held INTEGER,worker_token TEXT,evidence_ref TEXT,answer_ref TEXT,snapshot_json TEXT,counters_json TEXT,PRIMARY KEY(instance_id,run_id))','CREATE TABLE mohe_ai_config(instance_id TEXT PRIMARY KEY,enabled INTEGER,model TEXT,encrypted_key TEXT,external_authorized INTEGER,external_scope_version TEXT,version INTEGER)'] as $sql)$this->db->exec($sql);
  $this->temp=sys_get_temp_dir().'/mohe-r6-harness-'.bin2hex(random_bytes(8));mkdir($this->temp,0700);$this->private=new AiPrivateStorage($this->temp);$config=new AiConfigStore($this->db,'','fixture.r6',$this->private);$config->save(['enabled'=>true,'external_processing_authorized'=>true,'external_scope_version'=>AiConfigStore::QUESTION_SCOPE,'model'=>'fixture/model','api_key'=>'synthetic-fixture-key','version'=>0]);
  $model=function($view,$candidates,$configuration,$checkpoint,$repair=null,$phase='binding',$understanding=null){$this->models++;$checkpoint();$this->modelInputs[]=$view;
   $legacy=(new \app\services\ai\model\AiModelInputProjector())->modelView(['question'=>$view['question'],'history'=>[]]);$signals=$legacy['current']['signals'];$shape=($legacy['current']['semantic_intent']['goal']??'')==='metric_definition'?'definition':'summary';foreach(['trend','ranking','comparison']as$v)if(in_array($v,$signals,true))$shape=$v;$codes=array_values(array_intersect(['cash_performance','consume_amount'],$signals));$periods=in_array('TODAY',$signals,true)?[['kind'=>'relative_days','days'=>1,'end_offset_days'=>0]]:(in_array('THIS_MONTH',$signals,true)?[['kind'=>'month_offset','offset_months'=>0]]:[]);foreach($legacy['current']['date_terms'] as $term)if(($term['code']??'')==='EXPLICIT')$periods[]=['kind'=>'date_range','start'=>$term['start'],'end'=>$term['end']];$fallback=['object_kind'=>'store','object_term'=>'','operation'=>$shape,'metric_codes'=>$codes,'action_codes'=>[],'needs_metric_choice'=>$codes===[],'ranking'=>$shape==='ranking'?['direction'=>'top','limit'=>5]:['direction'=>'unspecified','limit'=>null],'periods'=>$periods,'scope'=>'authorized','unresolved_fragments'=>[]];$intent=$this->semanticIntent??$fallback;unset($intent['understanding']);
   if($phase==='understanding'){ if(is_array($this->understandingOverride)) return ['understanding'=>$this->understandingOverride,'usage'=>['input_tokens'=>20,'output_tokens'=>10]]; $values=[];$fields=[];$question=$view['question'];$terms=[];foreach((new \app\services\query\metric\MetricSemanticCatalog())->entries() as $code=>$entry) if(in_array($code,$intent['metric_codes'],true)) foreach($entry['terms'] as $term) if(mb_strpos($question,$term,0,'UTF-8')!==false){$terms[]=$term;break;} if($terms){$fields[]='metric_codes';$values['metric_terms']=$terms;} if($intent['periods']!==[]){$fields[]='periods';$values['periods']=$intent['periods'];} if($intent['operation']!=='summary'){$fields[]='operation';$values['operation']=$intent['operation'];} if(($intent['ranking']['direction']??'unspecified')!=='unspecified'){$fields[]='ranking';$values['ranking']=$intent['ranking'];} if(preg_match('/门店|店|会员|顾客|客户/u',$question)){$fields[]='object_kind';$values['object_kind']=$intent['object_kind'];} if(mb_strpos($question,'全部范围',0,'UTF-8')!==false){$fields[]='scope';$values['scope']='authorized';} $requirements=$fields?[['id'=>'r1','meaning'=>$question,'fields'=>$fields,'values'=>$values,'evidence'=>[['message_id'=>'current','quote'=>$question]]]]:[]; return ['understanding'=>['goal'=>$question,'requirements'=>$requirements,'status'=>$fields?'understood':'needs_clarification'],'usage'=>['input_tokens'=>20,'output_tokens'=>10]]; }
   if($phase==='binding_verification') {$review=$this->bindingVerificationSequence?array_shift($this->bindingVerificationSequence):(is_array($this->bindingVerificationOverride)?$this->bindingVerificationOverride:['decision'=>'accept','rejected_requirement_ids'=>[]]);$reply=['review'=>$review,'usage'=>['input_tokens'=>20,'output_tokens'=>10]];if($this->bindingReviewKind!==null)$reply['review_kind']=$this->bindingReviewKind;return $reply;}
   if(is_array($this->semanticIntentByRepair) && array_key_exists((string)$repair,$this->semanticIntentByRepair)) $intent=$this->semanticIntentByRepair[(string)$repair];
   if(($view['prior_query']??null)!==null&&!isset($intent['context_delta']))$intent['context_delta']=array_fill_keys(\app\services\ai\contract\AiIntentResultContract::DELTA_FIELDS,'inherit');
   if(!isset($intent['requirement_bindings'])){$boundCodes=$intent['metric_codes'];if(($intent['context_delta']['metric_codes']??null)==='inherit')$boundCodes=(array)($view['prior_query']['metric_codes']??[]);$metricRequirements=[];foreach((array)($understanding['requirements']??[])as$requirement)if(in_array('metric_codes',(array)($requirement['fields']??[]),true))$metricRequirements[]=$requirement['id'];$status=$boundCodes!==[]?'satisfied':($intent['needs_metric_choice']?'pending':'unavailable');$intent['requirement_bindings']=array_map(static function($id)use($status,$boundCodes){return['requirement_id'=>$id,'status'=>$status,'metric_codes'=>$status==='satisfied'?$boundCodes:[]];},$metricRequirements);}
   $intent['provenance']=['object_kind'=>['source'=>'customer','requirements'=>['r1']],'metric_codes'=>['source'=>$intent['metric_codes']===[]?'system':'customer','requirements'=>$intent['metric_codes']===[]?[]:['r1']],'operation'=>['source'=>in_array($intent['operation'],['summary','unknown'],true)?'system':'customer','requirements'=>in_array($intent['operation'],['summary','unknown'],true)?[]:['r1']],'periods'=>['source'=>$intent['periods']===[]?'system':'customer','requirements'=>$intent['periods']===[]?[]:['r1']],'ranking'=>['source'=>(($intent['ranking']['direction']??'unspecified')==='unspecified'&&($intent['ranking']['limit']??null)===null)?'system':'customer','requirements'=>(($intent['ranking']['direction']??'unspecified')==='unspecified'&&($intent['ranking']['limit']??null)===null)?[]:['r1']],'scope'=>['source'=>'system','requirements'=>[]]];return ['intent'=>$intent,'usage'=>['input_tokens'=>20,'output_tokens'=>10]];};
  $transaction=function($call){$this->queries++;return $call(new GroupPerformanceMetricReadServices(function(){return new R6Facts();},function(){}));};$this->gateway=new AiGatewayServices(new AiRunStore($this->db,'','fixture.r6'),$config,$this->private,'fixture.r6',new MetricReadViewStore($this->temp.'/views',$this->private->signingKey()),$model,$transaction);$this->auth=['terminal'=>$terminal,'account_id'=>7,'tenant_id'=>'0','can_use'=>true,'can_configure'=>true,'permission_version'=>'v1','scope_mode'=>'stores','store_ids'=>$authorizedStores,'personnel_data_authorized'=>false,'report_capability_code'=>'group_management_dashboard'];$this->context=$this->auth;$this->context['_refresh']=function(){return $this->auth;};$this->boot=$this->gateway->handle('bootstrap',$this->context,['client_session_id'=>'device1']);
 }
 public function start($question,$sourceRef=null,$history=[]){$input=['client_request_id'=>'request'.(++$this->sequence),'conversation_id'=>'conversation1','client_session_id'=>'device1','window_token'=>$this->boot['window_token'],'question'=>$question,'history'=>$history,'output_format'=>'screen','guidance_schema_version'=>'mohe-clarification-v2'];if($sourceRef!==null)$input['context_ref']=$sourceRef;$run=$this->gateway->handle('create',$this->context,$input);if(!isset($run['run_id']))return $run;return $this->gateway->handle('execute',$this->context,$this->binding($run)+$input,$run['run_id']);}
 public function binding($run){return ['client_session_id'=>'device1','generation'=>$run['generation'],'run_delivery_token'=>$run['run_delivery_token']];}
 public function input($run,$choices,$id=null,$revise=null){$c=$run['clarification'];$input=$this->binding($run)+['schema_version'=>'mohe-clarification-v2','clarification_id'=>$c['id'],'step_revision'=>$c['step_revision'],'intent_revision'=>$c['intent_revision'],'client_submission_id'=>$id??'answer'.(++$this->sequence),'choices'=>$choices];if($revise!==null)$input['revise_clarification_id']=$revise;return $input;}
 public function submit($run,$input){return $this->gateway->handle('clarify',$this->context,$input,$run['run_id']);} public function choose($run,$choices,$revise=null){return $this->submit($run,$this->input($run,$choices,null,$revise));} public function row($run){return $this->db->query('SELECT * FROM mohe_ai_run WHERE run_id='.$this->db->quote($run['run_id']))->fetch(PDO::FETCH_ASSOC);} public function step($run,$key,$round){r6hCheck($run['status']==='WAITING_CLARIFICATION','waiting');r6hCheck($run['clarification']['fields'][0]['key']===$key,'step '.$key);r6hCheck($run['clarification']['round_no']===$round,'round '.$round);} public function close(){foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->temp,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST)as$f){if($f->isDir())rmdir($f->getPathname());else unlink($f->getPathname());}rmdir($this->temp);}
}
