<?php
declare(strict_types=1);
require __DIR__.'/state-store-contract.php';

$db=new PDO('sqlite::memory:'); installAiStateFixture($db);
$now=1000000;
$store=new \app\services\ai\execution\AiRunStore($db,'','attempt.instance',function () use (&$now) { return $now; });
$r=$store->create($owner,'attempt1',$hash,$snapshot)['run']; $id=$r['run_id']; $g=$r['generation'];
$store->claim($owner,$id,$g,'worker');
checkState($store->snapshot($owner,$id,$g)===$snapshot,'snapshot roundtrip exact');
checkState($store->progress($owner,$id,$g,'worker','UNDERSTANDING')['progress_code']==='UNDERSTANDING','registered progress only');
rejectsState(function () use ($store,$owner,$id,$g) { $store->progress($owner,$id,$g,'worker','cash is 999'); },'AI_PROGRESS_INVALID');
rejectsState(function () use ($store,$owner,$id,$g,$hash) { $store->prepareAttempt($owner,$id,$g,'worker','p1','model',$hash,'siliconflow'); },'AI_COUNTER_SEQUENCE');
$store->reserve($owner,$id,$g,'worker','stage_count');
checkState($store->prepareAttempt($owner,$id,$g,'worker','p1','model',$hash,'siliconflow')['prepared'],'prepared atomically');
checkState(!$store->prepareAttempt($owner,$id,$g,'worker','p1','model',$hash,'siliconflow')['prepared'],'duplicate prepared cannot execute');
rejectsState(function () use ($store,$owner,$id,$g) { $store->prepareAttempt($owner,$id,$g,'worker','p1','model',str_repeat('f',64),'siliconflow'); },'AI_ATTEMPT_CONFLICT');
rejectsState(function () use ($store,$owner,$id,$g) { $store->publish($owner,$id,$g,'worker','e','a'); },'AI_ATTEMPT_UNRESOLVED');
checkState($store->sendAttempt($owner,$id,$g,'worker','p1'),'first send only');
checkState(!$store->sendAttempt($owner,$id,$g,'worker','p1'),'inflight must not replay');
rejectsState(function () use ($store,$owner,$id,$g) { $store->pauseForClarification($owner,$id,$g,'worker'); },'AI_ATTEMPT_UNRESOLVED');
$store->finishAttempt($owner,$id,$g,'worker','p1','SUCCEEDED',100,20);
$store->finishAttempt($owner,$id,$g,'worker','p1','SUCCEEDED',100,20);
checkState((int)$db->query('SELECT input_tokens FROM mohe_ai_attempt')->fetchColumn()===100,'only known numeric usage');
rejectsState(function () use ($store,$owner,$id,$g) { $store->finishAttempt($owner,$id,$g,'worker','p1','FAILED'); },'AI_ATTEMPT_TERMINAL');
$store->pauseForClarification($owner,$id,$g,'worker','clarification1');
checkState($store->get($owner,$id,$g)['clarification_ref']==='clarification1','clarification only reference');
$store->resume($owner,$id,$g,'worker2');
$store->reserve($owner,$id,$g,'worker2','model_recovery_count');
$store->prepareAttempt($owner,$id,$g,'worker2','p2','model',$hash,'siliconflow');
$store->sendAttempt($owner,$id,$g,'worker2','p2');
rejectsState(function () use ($store,$owner,$id,$g) { $store->finishAttempt($owner,$id,$g,'worker2','p2','UNKNOWN',0,0); },'AI_ATTEMPT_INVALID');
$store->finishAttempt($owner,$id,$g,'worker2','p2','UNKNOWN');
checkState($store->get($owner,$id,$g)['status']==='FAILED','unknown stops parent');
checkState($store->get($owner,$id,$g)['reason']==='ATTEMPT_UNKNOWN','unknown reason');
rejectsState(function () use ($store,$owner,$id,$g) { $store->publish($owner,$id,$g,'worker2','e','a'); },'AI_RUN_TERMINAL');
$store->release($owner,$id,$g,'worker2');
$r=$store->create($owner,'attempt2',$hash,$snapshot)['run']; $id=$r['run_id']; $g=$r['generation'];
$store->claim($owner,$id,$g,'worker');
$store->prepareAttempt($owner,$id,$g,'worker','q1','tool',$hash,'query'); $store->sendAttempt($owner,$id,$g,'worker','q1');
$store->cancel($owner,$id,$g); $store->cleanup();
checkState($db->query("SELECT state FROM mohe_ai_attempt WHERE attempt_code='q1'")->fetchColumn()==='UNKNOWN','supervisor classifies unresolved cancelled send');
$now+=86400000; $store->cleanup();
checkState((int)$db->query('SELECT COUNT(*) FROM mohe_ai_attempt')->fetchColumn()===0,'attempt metadata expires with Run');
echo 'PASS '.$checks." total state/Attempt checks (single send, usage, unknown and retention).\n";
