<?php
declare(strict_types=1);
require __DIR__.'/state-store-contract.php';
$db=new PDO('sqlite::memory:'); installAiStateFixture($db);
$now=2000000;
$store=new \app\services\ai\execution\AiRunStore($db,'','fixture.instance',function () use (&$now) { return $now; });
$r=$store->create($owner,'export1',$hash,$snapshot)['run']; $id=$r['run_id']; $g=$r['generation'];
$store->claim($owner,$id,$g,'parent1');
$called=0;
$store->exportFence($owner,$id,$g,'parent1','create',function () use (&$called) { ++$called; });
checkState($called===1,'export lifecycle action runs once');
$waiting=$store->waitForExport($owner,$id,$g,'parent1','handoff1');
checkState($waiting['status']==='WAITING_EXPORT' && $waiting['slot_held']===0 && $waiting['answer_ref']==='handoff1','parent waits without execution slot');
checkState($waiting['deadline_at']===$r['deadline_at'] && $waiting['expires_at']===$r['expires_at'],'export wait cannot extend budget or retention');
$store->exportFence($owner,$id,$g,'parent1','heartbeat',function () use (&$called) { ++$called; });
checkState($called===2,'child lifecycle fences while waiting');
$resumed=$store->resumeAfterExport($owner,$id,$g,'parent1','publisher1');
checkState($resumed['status']==='WORKFLOW_EXECUTING' && $resumed['slot_held']===1,'publication continuation reserves slot');
rejectsState(function () use ($store,$owner,$id,$g) { $store->resumeAfterExport($owner,$id,$g,'parent1','publisher2'); },'AI_WORKER_FENCED');
rejectsState(function () use ($store,$owner,$id,$g) { $store->exportFence($owner,$id,$g,'parent1','complete',function () {}); },'AI_WORKER_FENCED');
$store->publish($owner,$id,$g,'publisher1','evidence1','answer1');
$store->release($owner,$id,$g,'publisher1');
$store->exportFence($owner,$id,$g,'','download',function () use (&$called) { ++$called; });
checkState($called===3,'completed owner can download');
$r=$store->create($owner,'export2',$hash,$snapshot)['run']; $id=$r['run_id']; $g=$r['generation'];
$store->claim($owner,$id,$g,'parent2'); $store->waitForExport($owner,$id,$g,'parent2','handoff2');
$store->cancel($owner,$id,$g);
$store->exportFence($owner,$id,$g,'','cancel',function () use (&$called) { ++$called; });
checkState($called===4,'cancel reaches child after logical parent cancellation');
rejectsState(function () use ($store,$owner,$id,$g) { $store->exportFence($owner,$id,$g,'parent2','complete',function () {}); },'AI_RUN_TERMINAL');
rejectsState(function () use ($store,$owner,$id,$g) { $store->resumeAfterExport($owner,$id,$g,'parent2','publisher3'); },'AI_RUN_TERMINAL');
rejectsState(function () use ($store,$owner,$id,$g) { $store->exportFence($owner,$id,$g,'','download',function () {}); },'AI_EXPORT_NOT_PUBLISHED');
$r=$store->create($owner,'export3',$hash,$snapshot)['run']; $id=$r['run_id']; $g=$r['generation'];
$store->claim($owner,$id,$g,'parent3');
$partial=$store->publish($owner,$id,$g,'parent3','validated-evidence','validated-answer','data_only_export_failed');
checkState($partial['status']==='PARTIAL_SUCCEEDED' && $partial['reason']==='DATA_ONLY_EXPORT_FAILED','file-only degradation is explicit terminal');
checkState($store->cancel($owner,$id,$g)['status']==='PARTIAL_SUCCEEDED','partial delivery is immutable');
$store->release($owner,$id,$g,'parent3');
$now+=300000; $store->cleanup();
checkState($store->get($owner,$id,$g)['status']==='PARTIAL_SUCCEEDED','deadline cleanup cannot erase partial delivery');
rejectsState(function () use ($store,$owner,$id,$g) { $store->exportFence($owner,$id,$g,'','download',function () {}); },'AI_EXPORT_NOT_PUBLISHED');
echo 'PASS '.$checks." total state/export checks; SQLite transactions, no production DB.\n";
