-- upgrade_key: 20260729-002-inventory-entitlement-completion
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_inventory_shortage_policy` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `policy_scope` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `policy_value` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `updated_by` bigint(20) unsigned NOT NULL DEFAULT '0',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_scope_project` (`tenant_id`,`policy_scope`,`project_id`),
  KEY `idx_tenant_updated` (`tenant_id`,`updated_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='inventory shortage policy authority';

CREATE TABLE IF NOT EXISTS `eb_inventory_stock` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumable_product_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sku_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `product_unique` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `stock_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'GOOD',
  `stock_unit` varchar(32) NOT NULL DEFAULT '',
  `quantity_scale` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `available_quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `estimated_unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_store_sku_status` (`tenant_id`,`store_id`,`consumable_product_id`,`sku_id`,`stock_status`),
  KEY `idx_scope_store_product` (`tenant_id`,`organization_path`,`store_id`,`consumable_product_id`,`id`),
  KEY `idx_store_status` (`tenant_id`,`store_id`,`stock_status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='batch inventory stock aggregate authority';

CREATE TABLE IF NOT EXISTS `eb_inventory_batch` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stock_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `batch_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `manufactured_date` date NULL DEFAULT NULL,
  `expire_date` date NULL DEFAULT NULL,
  `received_at` int(11) unsigned NOT NULL DEFAULT '0',
  `available_quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cost_allocated_quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `batch_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stock_batch_no` (`stock_id`,`batch_no`),
  KEY `idx_stock_fefo` (`stock_id`,`batch_status`,`expire_date`,`received_at`,`id`),
  KEY `idx_stock_available` (`stock_id`,`batch_status`,`available_quantity_units`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='real inventory batch authority';

CREATE TABLE IF NOT EXISTS `eb_inventory_shortage_cost_cursor` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `stock_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `estimated_unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `allocated_quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scope_recipe_stock_cost` (`tenant_id`,`store_id`,`recipe_id`,`stock_id`,`estimated_unit_cost_cents`),
  KEY `idx_recipe_stock` (`tenant_id`,`store_id`,`recipe_id`,`stock_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='deterministic shortage estimated cost cursor';

CREATE TABLE IF NOT EXISTS `eb_inventory_consumption_receipt` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `receipt_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `idempotency_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `contract_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `operation_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CONSUME',
  `reversal_of_receipt_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_detail_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `policy_value` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `policy_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_formula_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `actual_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `estimated_shortage_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cost_complete_at_settlement` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `result_snapshot` mediumtext NOT NULL,
  `business_date` date NOT NULL,
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `settled_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_receipt_key` (`tenant_id`,`receipt_key`),
  UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`,`idempotency_key`),
  KEY `idx_source` (`tenant_id`,`source_type`,`source_id`,`source_detail_id`,`id`),
  KEY `idx_store_business_date` (`tenant_id`,`store_id`,`business_date`,`id`),
  KEY `idx_org_path_business_date` (`tenant_id`,`organization_path`,`business_date`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of_receipt_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='inventory completion idempotent receipt and historical snapshot';

CREATE TABLE IF NOT EXISTS `eb_inventory_batch_consumption_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fact_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `receipt_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `reversal_of` bigint(20) unsigned NOT NULL DEFAULT '0',
  `direction` smallint(6) NOT NULL DEFAULT '1',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_detail_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `recipe_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_formula_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `policy_value` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `policy_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumable_product_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumable_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `sku_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sku_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `stock_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `batch_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `batch_no_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `quantity_scale` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `actual_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cost_cursor_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cost_cursor_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `batch_version_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `batch_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `business_date` date NOT NULL,
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `settled_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_fact_key` (`tenant_id`,`fact_key`),
  KEY `idx_receipt` (`receipt_id`,`id`),
  KEY `idx_batch_time` (`tenant_id`,`batch_id`,`recorded_at`,`id`),
  KEY `idx_store_business_date` (`tenant_id`,`store_id`,`business_date`,`id`),
  KEY `idx_source` (`tenant_id`,`source_type`,`source_id`,`source_detail_id`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='append only real batch consumption fact';

CREATE TABLE IF NOT EXISTS `eb_inventory_shortage_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fact_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `receipt_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `reversal_of` bigint(20) unsigned NOT NULL DEFAULT '0',
  `direction` smallint(6) NOT NULL DEFAULT '1',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_detail_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `recipe_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recipe_formula_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `consumable_product_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumable_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `sku_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sku_name_snapshot` varchar(120) NOT NULL DEFAULT '',
  `stock_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity_scale` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `shortage_quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `estimated_unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `estimated_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cost_cursor_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cost_cursor_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `policy_value` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `policy_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `business_date` date NOT NULL,
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `settled_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_fact_key` (`tenant_id`,`fact_key`),
  KEY `idx_receipt` (`receipt_id`,`id`),
  KEY `idx_store_business_date` (`tenant_id`,`store_id`,`business_date`,`id`),
  KEY `idx_source` (`tenant_id`,`source_type`,`source_id`,`source_detail_id`,`id`),
  KEY `idx_stock_open` (`tenant_id`,`stock_id`,`recorded_at`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='append only inventory shortage fact, never a batch';

CREATE TABLE IF NOT EXISTS `eb_inventory_shortage_cost_adjustment` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `adjustment_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `shortage_fact_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `reversal_of` bigint(20) unsigned NOT NULL DEFAULT '0',
  `direction` smallint(6) NOT NULL DEFAULT '1',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `adjustment_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `allocated_quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0',
  `actual_unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `actual_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_adjustment_key` (`tenant_id`,`adjustment_key`),
  UNIQUE KEY `uk_shortage_adjustment_version` (`shortage_fact_id`,`adjustment_version`),
  KEY `idx_shortage` (`shortage_fact_id`,`id`),
  KEY `idx_store_time` (`tenant_id`,`store_id`,`recorded_at`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='append only actual shortage cost adjustment';

SELECT 'APPLY_OK' AS apply_result;
