-- upgrade_key: 20260729-017-cashier-v3-hang-order-authority-v1
-- MySQL 5.6.51 compatible. Run 01 before and 03 after this script.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_hang_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hang_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `hang_order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `contract_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_path_snapshot` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `workspace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `state_context_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `workspace_line_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `preparation_request_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `preparation_token` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `hang_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `room_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `room_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `room_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `room_time_slot_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `room_time_slot_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `room_guard_fingerprint` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `line_count` int(10) unsigned NOT NULL,
  `total_quantity` bigint(20) unsigned NOT NULL,
  `sale_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `entitlement_actual_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `hang_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `hang_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hang_order_id` (`hang_order_id`),
  UNIQUE KEY `uk_tenant_order_no` (`tenant_id`,`hang_order_no`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_tenant_command` (`tenant_id`,`command_idempotency_key`),
  UNIQUE KEY `uk_tenant_preparation` (`tenant_id`,`preparation_request_id`),
  KEY `idx_store_status_time` (`tenant_id`,`store_id`,`hang_status`,`occurred_at`,`id`),
  KEY `idx_room_status` (`tenant_id`,`store_id`,`room_id`,`hang_status`,`id`),
  KEY `idx_member_status` (`tenant_id`,`member_id`,`hang_status`,`id`),
  KEY `idx_workspace` (`tenant_id`,`workspace_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 authoritative hang order header';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_hang_order_line` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `hang_order_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `hang_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL,
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `workspace_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `line_no` int(10) unsigned NOT NULL,
  `line_role` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_version` bigint(20) unsigned NOT NULL,
  `detail_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `detail_version` bigint(20) unsigned NOT NULL,
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity` bigint(20) unsigned NOT NULL,
  `sale_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `entitlement_actual_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `service_object` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `is_experience` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `craftsmen_snapshot_json` text NOT NULL,
  `line_snapshot_json` longtext NOT NULL,
  `line_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `line_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hang_order_line_id` (`hang_order_line_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_order_workspace_line` (`tenant_id`,`hang_order_id`,`workspace_line_id`),
  KEY `idx_order_line` (`tenant_id`,`hang_order_id`,`line_no`,`id`),
  KEY `idx_scope_source` (`tenant_id`,`store_id`,`line_role`,`source_id`,`id`),
  KEY `idx_member_order` (`tenant_id`,`member_id`,`hang_order_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 frozen hang order lines';

SELECT 'APPLY_OK' AS apply_result;
