server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.html index.php index.htm;

    client_max_body_size 50m;

    location ~* \.php$ {
        proxy_pass http://mohe-platform-app:20700;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ @swoole;
    }

    location @swoole {
        proxy_pass http://mohe-platform-app:20700;
        proxy_http_version 1.1;
        proxy_read_timeout 360s;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
