-- upgrade_key: 20260729-001-customer-care-core
-- MySQL 5.6 compatible: no JSON type, CTE, window function, generated column or CHECK.
-- Fresh install requires 01 first. An interrupted 1-2 table install requires 05 READY first,
-- then this exact file creates only missing tables and 03 verifies the complete result.
-- CREATE IF NOT EXISTS never repairs drift.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_customer_care_task` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `task_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `create_idempotency_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `create_request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `business_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `business_store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `member_id` int(11) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `owner_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `task_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `title` varchar(128) NOT NULL DEFAULT '',
  `note` varchar(500) NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UNSTARTED',
  `is_visible` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `planned_at` int(11) unsigned NOT NULL DEFAULT '0',
  `planned_timezone` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Shanghai',
  `started_at` int(11) unsigned NOT NULL DEFAULT '0',
  `completed_at` int(11) unsigned NOT NULL DEFAULT '0',
  `voided_at` int(11) unsigned NOT NULL DEFAULT '0',
  `deleted_at` int(11) unsigned NOT NULL DEFAULT '0',
  `created_by_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_task_key` (`tenant_id`,`task_key`),
  UNIQUE KEY `uk_tenant_create_idem` (`tenant_id`,`create_idempotency_key`),
  KEY `idx_store_status_plan` (`tenant_id`,`business_store_id`,`status`,`is_visible`,`planned_at`,`id`),
  KEY `idx_owner_status_plan` (`tenant_id`,`owner_staff_id`,`status`,`is_visible`,`planned_at`,`id`),
  KEY `idx_member_plan` (`tenant_id`,`member_id`,`planned_at`,`id`),
  KEY `idx_org_path_plan` (`tenant_id`,`organization_path`,`planned_at`,`id`),
  KEY `idx_source` (`tenant_id`,`source_type`,`source_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='customer care task source of truth';

CREATE TABLE IF NOT EXISTS `eb_customer_care_record` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `record_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `business_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `business_store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `business_timezone_snapshot` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Shanghai',
  `operation_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `operation_store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `operation_organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `operation_organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `operation_organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `task_id` bigint(20) unsigned NULL DEFAULT NULL,
  `member_id` int(11) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `owner_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `record_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `followup_method` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `result_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `summary` varchar(255) NOT NULL DEFAULT '',
  `detail` text NOT NULL,
  `followed_at` int(11) unsigned NOT NULL DEFAULT '0',
  `follower_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `follower_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `follower_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `related_business_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `related_business_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `related_business_label_snapshot` varchar(128) NOT NULL DEFAULT '',
  `requires_next_followup` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `next_task_id` bigint(20) unsigned NULL DEFAULT NULL,
  `next_planned_at` int(11) unsigned NOT NULL DEFAULT '0',
  `next_owner_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `next_owner_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `next_owner_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NORMAL',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `business_date` date NOT NULL,
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `settled_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  `voided_at` int(11) unsigned NOT NULL DEFAULT '0',
  `voided_by_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `void_reason` varchar(255) NOT NULL DEFAULT '',
  `created_by_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_record_key` (`tenant_id`,`record_key`),
  UNIQUE KEY `uk_tenant_record_idem` (`tenant_id`,`command_idempotency_key`),
  UNIQUE KEY `uk_tenant_task_record` (`tenant_id`,`task_id`),
  UNIQUE KEY `uk_tenant_next_task` (`tenant_id`,`next_task_id`),
  KEY `idx_store_business_date` (`tenant_id`,`business_store_id`,`business_date`,`id`),
  KEY `idx_member_business_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_org_path_business_date` (`tenant_id`,`organization_path`,`business_date`,`id`),
  KEY `idx_status_recorded` (`tenant_id`,`status`,`recorded_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='immutable customer care formal record';

CREATE TABLE IF NOT EXISTS `eb_customer_care_operation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `operation_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `business_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `business_store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `operation_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `operation_store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `operation_organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `operation_organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `operation_organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `task_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `record_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `next_task_id_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `next_task_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_id` int(11) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `operation_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `task_status_before` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `task_status_after` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `record_status_before` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `record_status_after` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `task_version_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `task_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `record_version_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `record_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `owner_staff_id_before` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_staff_id_after` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_employee_id_before` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_employee_id_after` int(11) unsigned NOT NULL DEFAULT '0',
  `owner_name_snapshot_before` varchar(64) NOT NULL DEFAULT '',
  `owner_name_snapshot_after` varchar(64) NOT NULL DEFAULT '',
  `is_visible_before` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `is_visible_after` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `actor_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `actor_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `actor_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `reason` varchar(255) NOT NULL DEFAULT '',
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_operation_key` (`tenant_id`,`operation_key`),
  UNIQUE KEY `uk_tenant_operation_idem` (`tenant_id`,`command_idempotency_key`),
  KEY `idx_task_time` (`tenant_id`,`task_id`,`occurred_at`,`id`),
  KEY `idx_record_time` (`tenant_id`,`record_id`,`occurred_at`,`id`),
  KEY `idx_next_task_time` (`tenant_id`,`next_task_id_after`,`occurred_at`,`id`),
  KEY `idx_actor_time` (`tenant_id`,`actor_staff_id`,`occurred_at`,`id`),
  KEY `idx_store_time` (`tenant_id`,`business_store_id`,`occurred_at`,`id`),
  KEY `idx_org_path_time` (`tenant_id`,`organization_path`,`occurred_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='append only customer care operation receipt';

SELECT 'APPLY_OK' AS apply_result;
