-- upgrade_key: 20260801-003-cashier-v3-debt-repayment-authority
-- MySQL 5.6 compatible. This package creates empty V3-only authority tables.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_debt_authority` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `debt_id` int(11) unsigned NOT NULL,
  `debt_no` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL,
  `member_id` bigint(20) unsigned NOT NULL,
  `sales_order_record_id` bigint(20) unsigned NOT NULL,
  `sales_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_no_snapshot` varchar(64) NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `policy_version` bigint(20) unsigned NOT NULL,
  `authority_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` bigint(20) unsigned NOT NULL,
  `updated_at` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_debt_id` (`debt_id`),
  UNIQUE KEY `uk_tenant_debt_no` (`tenant_id`,`debt_no`),
  UNIQUE KEY `uk_tenant_checkout` (`tenant_id`,`checkout_request_id`),
  KEY `idx_scope_member_status` (`tenant_id`,`store_id`,`member_id`,`id`),
  KEY `idx_sales_order` (`tenant_id`,`sales_order_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 authority mapping for debt created by checkout';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_debt_repayment_draft` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `draft_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `workspace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `state_context_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL,
  `member_id` bigint(20) unsigned NOT NULL,
  `operator_id` bigint(20) unsigned NOT NULL,
  `debt_id` int(11) unsigned NOT NULL,
  `debt_no` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `repayment_amount_cents` bigint(20) unsigned NOT NULL,
  `debt_repaid_snapshot_cents` bigint(20) unsigned NOT NULL,
  `debt_version_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_lines_json` mediumtext NOT NULL,
  `draft_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `draft_version` bigint(20) unsigned NOT NULL,
  `prepare_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `last_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_draft_id` (`draft_id`),
  UNIQUE KEY `uk_tenant_workspace_debt` (`tenant_id`,`workspace_id`,`debt_id`),
  KEY `idx_scope_status` (`tenant_id`,`store_id`,`operator_id`,`draft_status`,`id`),
  KEY `idx_debt_version` (`debt_id`,`draft_version`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='eventless cashier v3 debt repayment draft';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_debt_repayment` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `repayment_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `repayment_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_path_snapshot` varchar(191) NOT NULL,
  `organization_name_snapshot` varchar(128) NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL,
  `member_id` bigint(20) unsigned NOT NULL,
  `member_name_snapshot` varchar(128) NOT NULL,
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL,
  `debt_id` int(11) unsigned NOT NULL,
  `debt_no` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_no_snapshot` varchar(64) NOT NULL,
  `repayment_amount_cents` bigint(20) unsigned NOT NULL,
  `debt_repaid_before_cents` bigint(20) unsigned NOT NULL,
  `debt_repaid_after_cents` bigint(20) unsigned NOT NULL,
  `debt_status_after` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `version` bigint(20) unsigned NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_repayment_id` (`repayment_id`),
  UNIQUE KEY `uk_repayment_no` (`repayment_no`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_tenant_command` (`tenant_id`,`command_idempotency_key`),
  KEY `idx_debt_time` (`debt_id`,`settled_at`,`id`),
  KEY `idx_scope_member_time` (`tenant_id`,`store_id`,`member_id`,`settled_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 settled debt repayment order authority';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_debt_repayment_collection` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `collection_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `repayment_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_line_no` int(10) unsigned NOT NULL,
  `payment_method` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_method_name_snapshot` varchar(32) NOT NULL,
  `amount_cents` bigint(20) unsigned NOT NULL,
  `external_transaction_no_snapshot` varchar(64) NOT NULL,
  `remark_snapshot` varchar(255) NOT NULL,
  `collection_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collection_id` (`collection_id`),
  UNIQUE KEY `uk_repayment_line` (`repayment_id`,`payment_line_no`),
  UNIQUE KEY `uk_tenant_natural` (`repayment_id`,`natural_key`),
  KEY `idx_repayment_method` (`repayment_id`,`payment_method`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 debt repayment collected payment lines';

SELECT 'APPLY_OK' AS apply_result;
