-- upgrade_key: 20260729-011-cashier-v3-sales-order-authority-v1
-- MySQL 5.6.51 compatible. Run 01 before and 03 after this script.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_sales_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `contract_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_path_snapshot` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '0 means guest',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_request_version` bigint(20) unsigned NOT NULL,
  `checkout_prepare_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_authority_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_aggregate_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_source_set_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `composition` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_document_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `line_count` int(10) unsigned NOT NULL DEFAULT '0',
  `total_quantity` bigint(20) unsigned NOT NULL DEFAULT '0',
  `original_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `discount_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sale_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `order_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_version` bigint(20) unsigned NOT NULL,
  `order_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reversal_of_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `reversal_reason_snapshot` varchar(255) NOT NULL DEFAULT '',
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_id` (`order_id`),
  UNIQUE KEY `uk_tenant_order_no` (`tenant_id`,`order_no`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_tenant_checkout` (`tenant_id`,`checkout_request_id`),
  KEY `idx_scope_date_status` (`tenant_id`,`store_id`,`business_date`,`order_status`,`id`),
  KEY `idx_scope_settled` (`tenant_id`,`store_id`,`settled_at`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of_order_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 authoritative settled sales order header';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_sales_order_line` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL,
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '0 means guest',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_request_version` bigint(20) unsigned NOT NULL,
  `checkout_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkout_line_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `line_no` int(10) unsigned NOT NULL,
  `item_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `item_type_name_snapshot` varchar(32) NOT NULL DEFAULT '',
  `item_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `item_version` bigint(20) unsigned NOT NULL,
  `item_code_snapshot` varchar(64) NOT NULL DEFAULT '',
  `item_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `category_id_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `category_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `quantity` bigint(20) unsigned NOT NULL,
  `original_amount_cents` bigint(20) unsigned NOT NULL,
  `discount_amount_cents` bigint(20) unsigned NOT NULL,
  `sale_amount_cents` bigint(20) unsigned NOT NULL,
  `line_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `line_version` bigint(20) unsigned NOT NULL,
  `line_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reversal_of_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_line_id` (`order_line_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  UNIQUE KEY `uk_order_checkout_line` (`tenant_id`,`order_id`,`checkout_line_id`),
  UNIQUE KEY `uk_checkout_line` (`tenant_id`,`checkout_request_id`,`checkout_line_id`),
  KEY `idx_order_line` (`tenant_id`,`order_id`,`line_no`,`id`),
  KEY `idx_scope_item` (`tenant_id`,`store_id`,`item_type`,`item_id`,`id`),
  KEY `idx_member_order` (`tenant_id`,`member_id`,`order_id`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of_line_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable formal-sale order lines';

SELECT 'APPLY_OK' AS apply_result;
