-- upgrade_key: 20260730-021-cashier-v3-card-operation-authority-v1
-- MySQL 5.6.51 compatible. Run 01 before and 03 after this script.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_card_state` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `card_holder_id` bigint(20) unsigned NOT NULL,
  `origin_order_id` bigint(20) unsigned NOT NULL,
  `origin_member_id` bigint(20) unsigned NOT NULL,
  `current_member_id` bigint(20) unsigned NOT NULL,
  `card_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'enabled',
  `status_reason_snapshot` varchar(500) NOT NULL DEFAULT '',
  `effective_write_start` bigint(20) unsigned NOT NULL DEFAULT '0',
  `effective_write_end` bigint(20) unsigned NOT NULL DEFAULT '0',
  `current_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `last_operation_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `created_at` bigint(20) unsigned NOT NULL,
  `updated_at` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_holder` (`tenant_id`,`card_holder_id`),
  KEY `idx_tenant_current_member` (`tenant_id`,`current_member_id`,`card_status`,`id`),
  KEY `idx_tenant_origin_order` (`tenant_id`,`origin_order_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 current card ownership and availability state';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_card_operation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `operation_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `operation_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `operation_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `operation_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `contract_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_path_snapshot` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `source_card_holder_id` bigint(20) unsigned NOT NULL,
  `source_card_holder_version` bigint(20) unsigned NOT NULL,
  `origin_order_id` bigint(20) unsigned NOT NULL,
  `origin_member_id` bigint(20) unsigned NOT NULL,
  `member_id_before` bigint(20) unsigned NOT NULL,
  `member_id_after` bigint(20) unsigned NOT NULL,
  `member_name_before_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_name_after_snapshot` varchar(128) NOT NULL DEFAULT '',
  `card_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `card_no_snapshot` varchar(128) NOT NULL DEFAULT '',
  `card_status_before` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `card_status_after` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `write_end_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `write_end_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `target_catalog_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `target_catalog_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `target_price_cents` bigint(20) NOT NULL DEFAULT '0',
  `source_remaining_value_cents` bigint(20) NOT NULL DEFAULT '0',
  `settlement_delta_cents` bigint(20) NOT NULL DEFAULT '0',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `reason_snapshot` varchar(500) NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_snapshot_json` mediumtext NOT NULL,
  `target_snapshot_json` mediumtext NOT NULL,
  `result_snapshot_json` mediumtext NOT NULL,
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recorded_at` bigint(20) unsigned NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_operation_id` (`operation_id`),
  UNIQUE KEY `uk_tenant_operation_no` (`tenant_id`,`operation_no`),
  UNIQUE KEY `uk_tenant_command` (`tenant_id`,`command_idempotency_key`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  KEY `idx_scope_card_time` (`tenant_id`,`store_id`,`source_card_holder_id`,`occurred_at`,`id`),
  KEY `idx_scope_member_time` (`tenant_id`,`store_id`,`member_id_after`,`occurred_at`,`id`),
  KEY `idx_checkout_request` (`tenant_id`,`checkout_request_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable card operation authority header';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_card_operation_line` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `operation_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `operation_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `line_no` int(10) unsigned NOT NULL,
  `line_role` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_detail_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `target_catalog_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity_delta` bigint(20) NOT NULL DEFAULT '0',
  `quantity_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `amount_cents` bigint(20) NOT NULL DEFAULT '0',
  `line_snapshot_json` mediumtext NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_operation_line_id` (`operation_line_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  KEY `idx_operation_line` (`tenant_id`,`operation_id`,`line_no`,`id`),
  KEY `idx_source_detail` (`tenant_id`,`source_detail_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable card operation detail lines';

SELECT 'APPLY_OK' AS apply_result;
