-- upgrade_key: 20260729-004-cashier-v3-checkout-settlement
-- MySQL 5.6 compatible. Run 01 before and 03 after this script.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_checkout_request` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'server generated stable checkout request id',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `workspace_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `state_context_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '0 means guest',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `request_version` bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT 'CAS version, always positive',
  `request_status` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'editing',
  `composition` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Shanghai',
  `operation_occurred_at` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'real preparation/edit operation time',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_document_no` varchar(64) NOT NULL DEFAULT '',
  `sales_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `receivable_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `selected_payment_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `balance_deduction_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `balance_authority_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `balance_account_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `balance_account_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `debt_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `debt_authority_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `debt_policy_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `cash_performance_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'sum of seven bookkeeping methods only',
  `entitlement_actual_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'trace amount, never receivable or sale',
  `authority_snapshot_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `authority_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `aggregate_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `creation_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `last_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `last_operation_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `last_operation` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `add_time` int(11) unsigned NOT NULL DEFAULT '0',
  `update_time` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_id` (`request_id`),
  UNIQUE KEY `uk_tenant_creation_idem` (`tenant_id`,`creation_idempotency_key`),
  KEY `idx_tenant_workspace_status` (`tenant_id`,`workspace_id`,`request_status`,`update_time`,`id`),
  KEY `idx_store_status_date` (`store_id`,`request_status`,`business_date`,`id`),
  KEY `idx_member_time` (`tenant_id`,`member_id`,`update_time`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`),
  KEY `idx_last_idempotency` (`tenant_id`,`last_idempotency_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='eventless cashier v3 checkout request aggregate';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_checkout_line_draft` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'server generated stable line id',
  `request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `draft_version` bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT 'request version that froze this row',
  `draft_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `line_role` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `authority_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_kind` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `entitlement_source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'authoritative card-benefit detail id; 0 for sale lines',
  `source_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity` int(10) unsigned NOT NULL DEFAULT '1',
  `original_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `discount_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `sale_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `entitlement_actual_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `source_code_snapshot` varchar(64) NOT NULL DEFAULT '',
  `project_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `category_id_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `category_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `line_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `sort_no` int(10) unsigned NOT NULL DEFAULT '0',
  `add_time` int(11) unsigned NOT NULL DEFAULT '0',
  `update_time` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_line_id` (`line_id`),
  UNIQUE KEY `uk_request_authority` (`request_id`,`line_role`,`authority_key`),
  KEY `idx_request_role_sort` (`request_id`,`line_role`,`sort_no`,`id`),
  KEY `idx_scope_member` (`tenant_id`,`store_id`,`member_id`,`id`),
  KEY `idx_source` (`tenant_id`,`source_type`,`source_id`,`id`),
  KEY `idx_project` (`tenant_id`,`project_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='eventless authoritative sale and entitlement line drafts';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_checkout_payment_draft` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `payment_draft_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'server generated stable payment draft id',
  `request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `draft_version` bigint(20) unsigned NOT NULL DEFAULT '1' COMMENT 'request version that froze this row',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `payment_authority_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `payment_method` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `external_transaction_no` varchar(64) NOT NULL DEFAULT '' COMMENT 'cashier trace note only; not proof of channel charge',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Asia/Shanghai',
  `operation_occurred_at` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'draft business time; not successful settlement time',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_document_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_document_no` varchar(64) NOT NULL DEFAULT '',
  `payment_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `draft_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'draft',
  `sort_no` int(10) unsigned NOT NULL DEFAULT '0',
  `add_time` int(11) unsigned NOT NULL DEFAULT '0',
  `update_time` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_draft_id` (`payment_draft_id`),
  UNIQUE KEY `uk_request_method` (`request_id`,`payment_method`),
  UNIQUE KEY `uk_request_payment_authority` (`request_id`,`payment_authority_key`),
  KEY `idx_request_sort` (`request_id`,`sort_no`,`id`),
  KEY `idx_scope_method_date` (`tenant_id`,`store_id`,`payment_method`,`business_date`,`id`),
  KEY `idx_source_document` (`tenant_id`,`source_document_type`,`source_document_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='eventless payment selections; never a payment_collected fact';

SELECT 'APPLY_OK' AS apply_result;
