-- upgrade_key: 20260729-007-cashier-v3-checkout-facts-v1
-- MySQL 5.6.51 compatible. Re-runnable only after the partial-create audit passes.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_sale_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fact_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_type` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_version` bigint(20) unsigned NOT NULL,
  `reversal_of` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_path_snapshot` varchar(512) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `item_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `item_code_snapshot` varchar(64) NOT NULL DEFAULT '',
  `item_name_snapshot` varchar(255) NOT NULL DEFAULT '',
  `category_id_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `category_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `quantity` bigint(20) unsigned NOT NULL,
  `original_amount_cents` bigint(20) NOT NULL,
  `discount_amount_cents` bigint(20) NOT NULL,
  `sale_amount_cents` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fact_id` (`fact_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  KEY `idx_scope_date_status` (`tenant_id`,`store_id`,`business_date`,`status`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_checkout_line` (`checkout_request_id`,`source_line_id`,`id`),
  KEY `idx_order_line` (`tenant_id`,`order_id`,`source_line_id`,`id`),
  KEY `idx_item_date` (`tenant_id`,`item_id`,`business_date`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable sale_completed line facts';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_payment_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fact_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_type` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_version` bigint(20) unsigned NOT NULL,
  `reversal_of` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_path_snapshot` varchar(512) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_method` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payment_authority_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `collection_reference` varchar(128) NOT NULL DEFAULT '',
  `amount_cents` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fact_id` (`fact_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  KEY `idx_scope_method_date` (`tenant_id`,`store_id`,`payment_method`,`business_date`,`status`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_checkout_line` (`checkout_request_id`,`source_line_id`,`id`),
  KEY `idx_order_line` (`tenant_id`,`order_id`,`source_line_id`,`id`),
  KEY `idx_payment_authority` (`tenant_id`,`payment_authority_key`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 seven-method payment_collected facts';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_balance_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fact_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_type` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_version` bigint(20) unsigned NOT NULL,
  `reversal_of` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_path_snapshot` varchar(512) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `balance_change_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `balance_account_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `account_version` bigint(20) unsigned NOT NULL,
  `principal_delta_cents` bigint(20) NOT NULL,
  `bonus_delta_cents` bigint(20) NOT NULL,
  `principal_after_cents` bigint(20) unsigned NOT NULL,
  `bonus_after_cents` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fact_id` (`fact_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  KEY `idx_scope_type_date` (`tenant_id`,`store_id`,`balance_change_type`,`business_date`,`status`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_checkout_line` (`checkout_request_id`,`source_line_id`,`id`),
  KEY `idx_order_line` (`tenant_id`,`order_id`,`source_line_id`,`id`),
  KEY `idx_account_version` (`tenant_id`,`balance_account_id`,`account_version`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 immutable balance_changed facts';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_performance_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `fact_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_type` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_direction` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `natural_key` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `fact_version` bigint(20) unsigned NOT NULL,
  `reversal_of` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_path_snapshot` varchar(512) NOT NULL DEFAULT '',
  `store_id` bigint(20) unsigned NOT NULL,
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL,
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_date` date NOT NULL,
  `business_timezone` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `settled_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `order_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `source_document_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `performance_type` varchar(48) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `employee_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `employee_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `employee_type_snapshot` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `employee_type_authority_version` bigint(20) unsigned NOT NULL DEFAULT '0',
  `role_snapshot` varchar(64) NOT NULL DEFAULT '',
  `allocation_weight_numerator` bigint(20) unsigned NOT NULL DEFAULT '0',
  `allocation_weight_denominator` bigint(20) unsigned NOT NULL,
  `allocation_base_amount_cents` bigint(20) NOT NULL,
  `amount_cents` bigint(20) NOT NULL,
  `rule_code_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `rule_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `rule_version_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fact_id` (`fact_id`),
  UNIQUE KEY `uk_tenant_natural` (`tenant_id`,`natural_key`),
  KEY `idx_scope_type_date` (`tenant_id`,`store_id`,`performance_type`,`business_date`,`status`,`id`),
  KEY `idx_org_date` (`tenant_id`,`organization_id`,`business_date`,`id`),
  KEY `idx_member_date` (`tenant_id`,`member_id`,`business_date`,`id`),
  KEY `idx_employee_date` (`tenant_id`,`employee_id`,`performance_type`,`business_date`,`id`),
  KEY `idx_checkout_line` (`checkout_request_id`,`source_line_id`,`id`),
  KEY `idx_order_line` (`tenant_id`,`order_id`,`source_line_id`,`id`),
  KEY `idx_reversal` (`tenant_id`,`reversal_of`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 materialized performance facts and allocations';

SELECT 'APPLY_OK' AS apply_result;
