-- upgrade_key: 20260728-003-cashier-v3-event-outbox
-- MySQL 5.6 compatible. Run 01 first and 03 after this script.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_business_event` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `event_key` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `event_type` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `event_version` int(10) unsigned NOT NULL DEFAULT '1',
  `aggregate_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `aggregate_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `aggregate_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `source_type` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_detail_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `reversal_of` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '0',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(255) NOT NULL DEFAULT '',
  `store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `member_id` int(11) unsigned NOT NULL DEFAULT '0',
  `operator_id` int(11) unsigned NOT NULL DEFAULT '0',
  `business_date` date NOT NULL,
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `settled_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  `aggregate_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `store_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `payload` mediumtext,
  `payload_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `route_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_no` (`event_no`),
  UNIQUE KEY `uk_event_key` (`event_key`),
  KEY `idx_command_idempotency` (`command_idempotency_key`),
  KEY `idx_aggregate` (`aggregate_type`,`aggregate_id`),
  KEY `idx_source` (`source_type`,`source_id`,`source_detail_id`),
  KEY `idx_date_store_type` (`business_date`,`store_id`,`event_type`),
  KEY `idx_member_time` (`member_id`,`occurred_at`),
  KEY `idx_recorded_at` (`recorded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 append-only business events';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_outbox` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `event_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `consumer_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '0',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(255) NOT NULL DEFAULT '',
  `store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `member_id` int(11) unsigned NOT NULL DEFAULT '0',
  `operator_id` int(11) unsigned NOT NULL DEFAULT '0',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '10' COMMENT '10 pending,20 processing,30 retry,40 success,50 manual failed',
  `attempts` int(10) unsigned NOT NULL DEFAULT '0',
  `available_at` int(11) unsigned NOT NULL DEFAULT '0',
  `lease_until` int(11) unsigned NOT NULL DEFAULT '0',
  `lease_owner` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `lease_token` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `fencing_generation` bigint(20) unsigned NOT NULL DEFAULT '0',
  `last_error` varchar(255) NOT NULL DEFAULT '',
  `last_error_at` int(11) unsigned NOT NULL DEFAULT '0',
  `processed_at` int(11) unsigned NOT NULL DEFAULT '0',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_consumer` (`event_id`,`consumer_code`),
  KEY `idx_consumer_status_available` (`consumer_code`,`status`,`available_at`,`id`),
  KEY `idx_consumer_status_lease` (`consumer_code`,`status`,`lease_until`,`id`),
  KEY `idx_event_no` (`event_no`),
  KEY `idx_tenant_store_status` (`tenant_id`,`store_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 generic event outbox';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_outbox_attempt` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `outbox_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `event_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumer_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `fencing_generation` bigint(20) unsigned NOT NULL DEFAULT '0',
  `attempt_no` int(10) unsigned NOT NULL DEFAULT '0',
  `operation` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `worker_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `lease_token` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `error_message` varchar(255) NOT NULL DEFAULT '',
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_outbox_generation` (`outbox_id`,`fencing_generation`),
  KEY `idx_event_consumer` (`event_id`,`consumer_code`),
  KEY `idx_occurred_at` (`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 outbox lease audit';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_consumer_once` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `event_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumer_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `effect_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `metadata` text,
  `succeeded_at` int(11) unsigned NOT NULL DEFAULT '0',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_consumer` (`event_id`,`consumer_code`),
  UNIQUE KEY `uk_consumer_effect` (`consumer_code`,`effect_key`),
  KEY `idx_succeeded_at` (`succeeded_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 consumer exactly-once marker';

SELECT 'APPLY_OK' AS apply_result;
