-- upgrade_key: 20260730-002-inventory-batch-transfer
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS `eb_inventory_batch_transfer_document` (
 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `transfer_no` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '', `idempotency_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '', `request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
 `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '', `from_location_id` bigint(20) unsigned NOT NULL DEFAULT '0', `to_location_id` bigint(20) unsigned NOT NULL DEFAULT '0', `store_id` bigint(20) unsigned NOT NULL DEFAULT '0', `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0', `document_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CONFIRMED', `remark` varchar(500) NOT NULL DEFAULT '', `business_date` date NOT NULL, `confirmed_at` int(11) unsigned NOT NULL DEFAULT '0', `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`), UNIQUE KEY `uk_tenant_idempotency` (`tenant_id`,`idempotency_key`), UNIQUE KEY `uk_tenant_transfer_no` (`tenant_id`,`transfer_no`), KEY `idx_from_date` (`tenant_id`,`from_location_id`,`business_date`,`id`), KEY `idx_to_date` (`tenant_id`,`to_location_id`,`business_date`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='confirmed batch inventory transfer authority';
CREATE TABLE IF NOT EXISTS `eb_inventory_batch_transfer_line` (
 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `document_id` bigint(20) unsigned NOT NULL DEFAULT '0', `line_no` int(10) unsigned NOT NULL DEFAULT '0', `from_stock_id` bigint(20) unsigned NOT NULL DEFAULT '0', `to_stock_id` bigint(20) unsigned NOT NULL DEFAULT '0', `from_batch_id` bigint(20) unsigned NOT NULL DEFAULT '0', `to_batch_id` bigint(20) unsigned NOT NULL DEFAULT '0', `origin_batch_id` bigint(20) unsigned NOT NULL DEFAULT '0', `quantity_units` bigint(20) unsigned NOT NULL DEFAULT '0', `unit_cost_cents` bigint(20) unsigned NOT NULL DEFAULT '0', `created_at` int(11) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`), UNIQUE KEY `uk_document_source_batch` (`document_id`,`from_batch_id`), KEY `idx_origin` (`origin_batch_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='batch-level transfer lineage';
