CREATE TABLE IF NOT EXISTS `eb_cashier_v3_service_record_void_operation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `operation_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `operation_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `service_fact_id` bigint(20) unsigned NOT NULL,
  `service_record_no_snapshot` varchar(64) NOT NULL DEFAULT '',
  `checkout_request_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reason_snapshot` varchar(255) NOT NULL DEFAULT '',
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operator_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `restored_quantity` bigint(20) unsigned NOT NULL DEFAULT '0',
  `consumption_performance_amount_cents` bigint(20) NOT NULL DEFAULT '0',
  `labor_performance_amount_cents` bigint(20) NOT NULL DEFAULT '0',
  `labor_fee_amount_cents` bigint(20) NOT NULL DEFAULT '0',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'succeeded',
  `business_date` date NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `settled_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recorded_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `created_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `updated_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_void_operation_id` (`operation_id`),
  UNIQUE KEY `uk_service_void_operation_no` (`tenant_id`,`operation_no`),
  UNIQUE KEY `uk_service_void_service_fact` (`tenant_id`,`service_fact_id`),
  UNIQUE KEY `uk_service_void_command` (`tenant_id`,`command_idempotency_key`),
  KEY `idx_service_void_store_date` (`tenant_id`,`store_id`,`business_date`,`id`),
  KEY `idx_service_void_member_date` (`tenant_id`,`member_id`,`occurred_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 service record void operation ledger';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_entitlement_reversal_fact` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `reversal_fact_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `operation_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `original_writeoff_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `service_fact_id` bigint(20) unsigned NOT NULL,
  `holder_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `quantity` bigint(20) unsigned NOT NULL DEFAULT '0',
  `reversal_of` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `business_event_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `operator_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `business_date` date NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `settled_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `recorded_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_entitlement_reversal_fact_id` (`reversal_fact_id`),
  UNIQUE KEY `uk_entitlement_reversal_operation` (`operation_id`),
  UNIQUE KEY `uk_entitlement_reversal_command` (`tenant_id`,`command_idempotency_key`),
  KEY `idx_entitlement_reversal_source` (`tenant_id`,`service_fact_id`,`id`),
  KEY `idx_entitlement_reversal_detail` (`tenant_id`,`source_detail_id`,`occurred_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 entitlement quantity reversal facts';

SELECT 'APPLY_OK' AS apply_result;
