-- upgrade_key: 20260803-005-cashier-v3-issued-card-rule-state-v1
-- MySQL 5.6 compatible. No historic holder/card row is read or changed.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_card_rule_state` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `state_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `receipt_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `sales_order_line_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `card_holder_id` bigint(20) unsigned NOT NULL,
  `member_id` bigint(20) unsigned NOT NULL,
  `issue_store_id` bigint(20) unsigned NOT NULL,
  `catalog_product_id` bigint(20) unsigned NOT NULL,
  `catalog_sku_id` bigint(20) unsigned NOT NULL,
  `rule_type` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `rule_version` int(10) unsigned NOT NULL,
  `definition_version` bigint(20) unsigned NOT NULL,
  `choice_limit` int(10) unsigned NOT NULL DEFAULT '0',
  `selected_kind_count` int(10) unsigned NOT NULL DEFAULT '0',
  `shared_total_times` int(10) unsigned NOT NULL DEFAULT '0',
  `shared_remaining_times` int(10) unsigned NOT NULL DEFAULT '0',
  `validity_mode` tinyint(3) unsigned NOT NULL,
  `valid_from` bigint(20) unsigned NOT NULL DEFAULT '0',
  `valid_through` bigint(20) unsigned NOT NULL DEFAULT '0',
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `definition_snapshot_json` mediumtext NOT NULL,
  `state_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_state` (`tenant_id`,`state_id`),
  UNIQUE KEY `uk_tenant_receipt` (`tenant_id`,`receipt_id`),
  UNIQUE KEY `uk_tenant_holder` (`tenant_id`,`card_holder_id`),
  KEY `idx_member_status` (`tenant_id`,`member_id`,`status`,`id`),
  KEY `idx_issue_store` (`tenant_id`,`issue_store_id`,`occurred_at`,`id`),
  KEY `idx_sales_line` (`tenant_id`,`sales_order_line_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 issued card rule state';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_card_rule_component` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `component_state_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `rule_state_id` bigint(20) unsigned NOT NULL,
  `card_holder_id` bigint(20) unsigned NOT NULL,
  `legacy_detail_id` bigint(20) unsigned NOT NULL,
  `relation_id` bigint(20) unsigned NOT NULL,
  `project_product_id` bigint(20) unsigned NOT NULL,
  `project_sku_id` bigint(20) unsigned NOT NULL,
  `project_sku_unique` varchar(255) NOT NULL,
  `project_type` tinyint(3) unsigned NOT NULL,
  `project_name_snapshot` varchar(255) NOT NULL,
  `total_times` int(10) unsigned NOT NULL DEFAULT '0',
  `remaining_times` int(10) unsigned NOT NULL DEFAULT '0',
  `writeoff_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `selection_status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `selected_at` bigint(20) unsigned NOT NULL DEFAULT '0',
  `selected_store_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `immutable_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `component_snapshot_json` mediumtext NOT NULL,
  `state_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` bigint(20) unsigned NOT NULL,
  `recorded_at` bigint(20) unsigned NOT NULL,
  `add_time` bigint(20) unsigned NOT NULL,
  `update_time` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_component` (`tenant_id`,`component_state_id`),
  UNIQUE KEY `uk_state_relation` (`rule_state_id`,`relation_id`),
  UNIQUE KEY `uk_tenant_legacy_detail` (`tenant_id`,`legacy_detail_id`),
  KEY `idx_holder_status` (`tenant_id`,`card_holder_id`,`status`,`id`),
  KEY `idx_project_status` (`tenant_id`,`project_product_id`,`status`,`id`),
  KEY `idx_state_selection` (`rule_state_id`,`selection_status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='cashier v3 issued card rule component state';

SELECT 'APPLY_OK' AS apply_result;
