<template>
  <div>
    <Card :bordered="false"><Form inline><FormItem><Input v-model="query.keyword" placeholder="资料名称/文件名" @on-enter="load"/></FormItem><FormItem><Button type="primary" @click="open()">新增培训资料</Button></FormItem></Form></Card>
    <Card :bordered="false" class="ivu-mt"><Table :columns="columns" :data="list" :loading="loading"><template slot="action" slot-scope="{row}"><a @click="open(row)">编辑</a><Divider type="vertical"/><a @click="changeStatus(row, row.status === 1 ? 2 : 1)">{{row.status === 1 ? '下架' : '发布'}}</a></template></Table><Page class="mt15" :total="total" :current="query.page" @on-change="p=>{query.page=p;load()}"/></Card>
    <Modal v-model="visible" title="培训资料" @on-ok="save" width="680"><Form :label-width="100"><FormItem label="资料名称"><Input v-model="form.title"/></FormItem><FormItem label="分类"><Input v-model="form.category" placeholder="如：库存管理、门店收银"/></FormItem><FormItem label="版本"><Input v-model="form.version"/></FormItem><FormItem label="资料文件"><Upload :action="uploadUrl" :headers="header" :show-upload-list="false" :on-success="uploaded" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx"><Button icon="ios-cloud-upload-outline">上传文件</Button></Upload><span v-if="form.file_name" class="ml10">{{form.file_name}}</span></FormItem><FormItem label="适用端"><CheckboxGroup v-model="clients"><Checkbox label="admin">总后台</Checkbox><Checkbox label="store">门店后台</Checkbox><Checkbox label="mobile">手机端</Checkbox></CheckboxGroup></FormItem><FormItem label="必读"><i-switch v-model="form.is_required" :true-value="1" :false-value="0"/></FormItem><FormItem label="简介"><Input v-model="form.summary" type="textarea"/></FormItem></Form></Modal>
  </div>
</template>
<script>
import Setting from '@/setting'; import util from '@/libs/util'; import {trainingDocumentList,trainingDocumentSave,trainingDocumentStatus} from '@/api/trainingDocument';
export default {data(){return {loading:false,total:0,list:[],visible:false,query:{page:1,limit:20,keyword:''},clients:['admin','store','mobile'],form:this.empty(),uploadUrl:Setting.apiBaseURL+'/training/document/upload',header:{'Authori-zation':'Bearer '+util.cookies.get('token')},columns:[{title:'资料名称',key:'title',minWidth:180},{title:'分类',key:'category',width:120},{title:'版本',key:'version',width:90},{title:'文件',key:'file_name',minWidth:180},{title:'下载次数',key:'download_count',width:100},{title:'状态',key:'status',width:90,render:(h,p)=>h('span',p.row.status===1?'已发布':p.row.status===2?'已下架':'草稿')},{title:'操作',slot:'action',width:140}] }},created(){this.load()},methods:{empty(){return {id:0,title:'',category:'',version:'V1.0',file_name:'',file_path:'',file_ext:'',file_size:0,summary:'',is_required:0,allow_download:1,status:0}},load(){this.loading=true;trainingDocumentList(this.query).then(r=>{this.list=r.data.list;this.total=r.data.count}).finally(()=>this.loading=false)},open(row){this.form=Object.assign(this.empty(),row||{});this.clients=this.form.client_types&&this.form.client_types!=='all'?this.form.client_types.split(','):['admin','store','mobile'];this.visible=true},uploaded(r){Object.assign(this.form,r.data);this.$Message.success('文件上传成功')},save(){this.form.client_types=this.clients.join(',');trainingDocumentSave(this.form).then(()=>{this.$Message.success('保存成功');this.load()})},changeStatus(row,status){trainingDocumentStatus(row.id,status).then(()=>this.load())}}}
</script>
