<?php

namespace app\services\customer\care;

final class CustomerCareErrorCode
{
    public const INVALID_ARGUMENT = 'CARE_INVALID_ARGUMENT';
    public const INVALID_IDEMPOTENCY_KEY = 'CARE_INVALID_IDEMPOTENCY_KEY';
    public const IDEMPOTENCY_CONFLICT = 'CARE_IDEMPOTENCY_CONFLICT';
    public const NATURAL_KEY_CONFLICT = 'CARE_NATURAL_KEY_CONFLICT';
    public const TASK_NOT_FOUND = 'CARE_TASK_NOT_FOUND';
    public const RECORD_NOT_FOUND = 'CARE_RECORD_NOT_FOUND';
    public const VERSION_CONFLICT = 'CARE_VERSION_CONFLICT';
    public const INVALID_TASK_TRANSITION = 'CARE_INVALID_TASK_TRANSITION';
    public const INVALID_RECORD_TRANSITION = 'CARE_INVALID_RECORD_TRANSITION';
    public const OWNER_REQUIRED = 'CARE_OWNER_REQUIRED';
    public const BUSINESS_STORE_FORBIDDEN = 'CARE_BUSINESS_STORE_FORBIDDEN';
    public const REASSIGN_PERMISSION_REQUIRED = 'CARE_REASSIGN_PERMISSION_REQUIRED';
    public const ASSIGNEE_INACTIVE = 'CARE_ASSIGNEE_INACTIVE';
    public const CROSS_STORE_REASSIGN_FORBIDDEN = 'CARE_CROSS_STORE_REASSIGN_FORBIDDEN';
    public const APPOINTMENT_UNAVAILABLE = 'CARE_APPOINTMENT_UNAVAILABLE';
    public const REPOSITORY_CONFLICT = 'CARE_REPOSITORY_CONFLICT';
}
