-- upgrade_key: 20260729-005-c3-service-order-authority
-- MySQL 5.6.51 compatible. Run 01 first and 03 afterwards.
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_service_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `service_order_no` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_path` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `organization_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `business_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `business_store_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `member_id` int(11) unsigned NOT NULL DEFAULT '0',
  `member_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `source_type` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `source_no_snapshot` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_version_snapshot` bigint(20) unsigned NOT NULL DEFAULT '0',
  `room_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `room_name_snapshot` varchar(100) NOT NULL DEFAULT '',
  `participant_employee_ids_json` text NOT NULL,
  `status` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'OPEN',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `business_date` date NOT NULL,
  `service_started_at` int(11) unsigned NOT NULL DEFAULT '0',
  `pending_checkout_at` int(11) unsigned NOT NULL DEFAULT '0',
  `completed_at` int(11) unsigned NOT NULL DEFAULT '0',
  `cancelled_at` int(11) unsigned NOT NULL DEFAULT '0',
  `voided_at` int(11) unsigned NOT NULL DEFAULT '0',
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  `created_by_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `created_by_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `created_by_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_service_order_no` (`tenant_id`,`service_order_no`),
  KEY `idx_store_status_time` (`tenant_id`,`business_store_id`,`status`,`occurred_at`,`id`),
  KEY `idx_member_status_time` (`tenant_id`,`member_id`,`status`,`occurred_at`,`id`),
  KEY `idx_source` (`tenant_id`,`source_type`,`source_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='C3 authoritative service order';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_service_order_line` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `service_order_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `line_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `entitlement_source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `entitlement_instance_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `project_name_snapshot` varchar(128) NOT NULL DEFAULT '',
  `occupied_times` int(11) unsigned NOT NULL DEFAULT '0',
  `service_target` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'SELF',
  `is_experience` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `artisan_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `artisan_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `artisan_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
  `version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_order_line` (`tenant_id`,`service_order_id`,`line_key`),
  KEY `idx_tenant_detail_order` (`tenant_id`,`entitlement_source_detail_id`,`service_order_id`,`id`,`status`),
  KEY `idx_tenant_order_line` (`tenant_id`,`service_order_id`,`id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='C3 service order entitlement occupation line';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_service_order_entitlement_guard` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `entitlement_source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `current_version` bigint(20) unsigned NOT NULL DEFAULT '1',
  `last_action` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_entitlement_detail` (`tenant_id`,`entitlement_source_detail_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='C3 empty-range-safe entitlement occupation guard';

CREATE TABLE IF NOT EXISTS `eb_cashier_v3_service_order_operation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `operation_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `command_idempotency_key` varchar(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `request_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `tenant_id` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `business_store_id` int(11) unsigned NOT NULL DEFAULT '0',
  `operation_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `service_order_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `line_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `entitlement_source_detail_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `status_before` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `status_after` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `service_order_version_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `service_order_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `line_version_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `line_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `occupied_times_before` int(11) unsigned NOT NULL DEFAULT '0',
  `occupied_times_after` int(11) unsigned NOT NULL DEFAULT '0',
  `guard_version_before` bigint(20) unsigned NOT NULL DEFAULT '0',
  `guard_version_after` bigint(20) unsigned NOT NULL DEFAULT '0',
  `actor_staff_id` int(11) unsigned NOT NULL DEFAULT '0',
  `actor_employee_id` int(11) unsigned NOT NULL DEFAULT '0',
  `actor_name_snapshot` varchar(64) NOT NULL DEFAULT '',
  `reason` varchar(255) NOT NULL DEFAULT '',
  `result_json` text NOT NULL,
  `occurred_at` int(11) unsigned NOT NULL DEFAULT '0',
  `recorded_at` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_operation_key` (`tenant_id`,`operation_key`),
  UNIQUE KEY `uk_tenant_command_idem` (`tenant_id`,`command_idempotency_key`),
  KEY `idx_order_time` (`tenant_id`,`service_order_id`,`occurred_at`,`id`),
  KEY `idx_detail_time` (`tenant_id`,`entitlement_source_detail_id`,`occurred_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='append only C3 service order operation';

SELECT 'APPLY_OK' AS apply_result;
