<template>
  <div class="trial">
    <h3>已发布版本真实试问</h3><p>点击后将调用客户 SiliconFlow，可能消耗额度，并按当前账号权限查询经营数据。离开此模块会请求取消未完成任务。</p>
    <label>输出形式<select v-model="format" :disabled="active || sending"><option value="screen">仅查看数据</option><option value="screen_and_xlsx">数据和 Excel</option></select></label>
    <div class="actions"><button :disabled="active || sending || !question.trim()" @click="start">{{ pendingCreate ? '重试确认同次试问' : '真实试问（确认费用后运行）' }}</button><button :disabled="!active || cancelling" @click="cancel">停止试问</button></div>
    <p role="status">{{ progress }}</p><p v-if="error" role="alert" class="error">{{ error }}</p>
    <div v-if="clarification && !cancelling" class="guidance"><p>第 {{ clarification.round_no }} 步 · 最多 {{ clarification.max_clarification_rounds }} 步</p><p v-for="item in clarification.confirmed_summary" :key="item.label">{{ item.label }}：{{ item.value }}</p><h4>{{ revise ? '修改：' + revise.question : clarification.question }}</h4>
      <div v-for="field in currentFields" :key="field.key"><label v-if="field.type === 'date'">{{ field.label }}<input v-model="choices[field.key]" type="date" :aria-label="field.label" :min="field.min" :max="field.max" :disabled="sending || !!pendingClarify"></label><fieldset v-else><legend>{{ field.label }}</legend><label v-for="option in field.options" :key="option.value" class="choice"><input v-model="choices[field.key]" type="radio" :name="field.key" :value="option.value" :disabled="sending || !!pendingClarify">{{ option.label }}</label></fieldset></div>
      <button :disabled="sending" @click="clarify">{{ pendingClarify ? '重试确认' : '确认并继续' }}</button><details v-if="clarification.revisable_steps && clarification.revisable_steps.length"><summary>修改已确认条件</summary><button v-for="step in clarification.revisable_steps" :key="step.id" :disabled="sending || !!pendingClarify" @click="editStep(step)">{{ step.question }}</button><button :disabled="sending || !!pendingClarify" @click="editStep(null)">返回当前问题</button></details>
    </div>
    <div v-if="answer"><p>{{ answer.summary }}</p><div class="cards"><article v-for="(card, index) in answer.cards" :key="index"><h4>{{ card.metric_name }}</h4><strong>{{ card.display_value }}{{ card.unit }}</strong><p>{{ card.period_label }}</p><details v-if="card.tooltip"><summary>统计口径</summary><p v-if="typeof card.tooltip === 'string'">{{ card.tooltip }}</p><template v-else><p v-for="(line, key) in card.tooltip" :key="key">{{ line }}</p></template></details></article></div><div v-if="answer.table" class="table-scroll"><table><thead><tr><th v-for="column in answer.table.columns" :key="column.key">{{ column.label }}</th></tr></thead><tbody><tr v-for="(row, index) in answer.table.rows" :key="index"><td v-for="column in answer.table.columns" :key="column.key">{{ row[column.key] == null ? '—' : row[column.key] }}</td></tr></tbody></table></div><button v-if="answer.export && answer.export.file_ref" :disabled="downloading" @click="download">下载 Excel</button></div>
    <details v-if="run && run.management_trace" open><summary>执行轨迹（已发布版本）</summary><pre>{{ JSON.stringify(run.management_trace, null, 2) }}</pre></details>
    <ai-confirm ref="confirmation" />
  </div>
</template>
<script>
import request from '@/api/moheAi';
import AiConfirm from './confirm.vue';
import { newId, isTerminal, acceptRun } from '../../../../../shared/mohe-ai/device-session.mjs';
import { GUIDANCE_SCHEMA, validateClarification, clarificationKey, clarificationSubmission } from '../../../../../shared/mohe-ai/clarification-state.mjs';
export default {
  name: 'MoheAiManagementTrial', components: { AiConfirm }, props: { question: { type: String, default: '' } },
  data() { return { client: newId(), conversation: newId(), run: null, format: 'screen', progress: '', error: '', sending: false, cancelling: false, downloading: false, choices: {}, revise: null, pendingCreate: null, pendingClarify: null, disposed: false, timer: null }; },
  computed: { active() { return this.run && !isTerminal(this.run.status); }, answer() { return this.run && ['COMPLETED', 'PARTIAL_SUCCEEDED'].includes(this.run.status) ? this.run.answer : null; }, clarification() { return this.run && this.run.status === 'WAITING_CLARIFICATION' ? this.run.clarification : null; }, currentFields() { return this.revise ? this.revise.fields : this.clarification ? this.clarification.fields : []; } },
  beforeDestroy() { this.disposed = true; clearTimeout(this.timer); this.cancel(); },
  deactivated() { this.disposed = true; clearTimeout(this.timer); this.cancel(); },
  activated() { this.disposed = false; if (this.active) this.schedule(); },
  methods: {
    binding() { return { client_session_id: this.client, run_delivery_token: this.run.run_delivery_token, generation: this.run.generation }; },
    update(value) { const old = this.run; const oldKey = old && old.clarification ? clarificationKey(old.clarification) : null; this.run = acceptRun(old, value); if (!this.run) return; clearTimeout(this.timer); this.progress = typeof this.run.progress === 'string' ? this.run.progress : (this.run.progress && this.run.progress.message) || '正在处理'; if (this.clarification) { try { validateClarification(this.clarification, GUIDANCE_SCHEMA); } catch (e) { this.error = e.message; this.cancel(); return; } if (clarificationKey(this.clarification) !== oldKey) { this.pendingClarify = null; this.editStep(null); } } if (!this.active) { this.cancelling = false; this.progress = this.run.status === 'CANCELLED' ? '已取消' : this.run.message || this.progress; } else if (!this.clarification || this.cancelling) this.schedule(); },
    schedule() { clearTimeout(this.timer); if (!this.disposed && this.active) this.timer = setTimeout(this.poll, 1000); },
    async poll() { if (!this.active || this.disposed) return; try { this.update(await request('GET', '/runs/' + encodeURIComponent(this.run.run_id), this.binding())); } catch (_) { this.progress = this.cancelling ? '暂未确认取消结果，正在重试查询。' : '连接暂时中断，正在确认任务状态。'; this.schedule(); } },
    async start() { if (this.active || this.sending || !this.question.trim()) return; if (!this.pendingCreate && !await this.$refs.confirmation.open('将使用已发布版本调用客户 SiliconFlow 并读取授权经营数据，可能消耗客户额度。确认开始真实试问？', '真实试问与费用确认')) return; if (this.disposed) return; this.sending = true; this.error = ''; try { if (!this.pendingCreate) { const boot = await request('GET', '/bootstrap', { client_session_id: this.client }); if (!boot.enabled) throw new Error(boot.disabled_reason || '请先完成配置并启用可用能力。'); this.pendingCreate = { client_request_id: newId(), conversation_id: this.conversation, client_session_id: this.client, window_token: boot.window_token, question: this.question.trim(), history: [], output_format: this.format, guidance_schema_version: GUIDANCE_SCHEMA }; } const submitted = this.pendingCreate; this.run = null; this.progress = '正在接纳试问'; const accepted = await request('POST', '/runs', submitted); if (accepted.accepted === false) { this.pendingCreate = null; this.progress = accepted.message || '当前使用人数较多，请稍后再试。'; return; } this.update(accepted); this.pendingCreate = null; if (this.disposed) { await this.cancel(); return; } if (this.active) this.update(await request('POST', '/runs/' + encodeURIComponent(this.run.run_id) + '/execute', { ...this.binding(), question: submitted.question, history: [], output_format: submitted.output_format })); } catch (e) { this.error = e.responseKnown ? e.message : '请求结果暂未确认，请重试确认同次试问。'; if (!this.run && e.responseKnown) this.pendingCreate = null; if (this.run) this.schedule(); } finally { this.sending = false; } },
    editStep(step) { this.revise = step; const values = {}; (step ? step.fields : this.clarification.fields).forEach(field => { values[field.key] = step && step.choices[field.key] || ''; }); this.choices = values; },
    async clarify() { if (this.sending || !this.clarification) return; this.error = ''; if (!this.pendingClarify) { if (this.currentFields.some(field => !this.choices[field.key])) { this.error = '请完成当前选择。'; return; } this.pendingClarify = { ...this.binding(), ...clarificationSubmission(this.clarification, this.choices, newId(), this.revise ? this.revise.id : null) }; } this.sending = true; try { this.update(await request('POST', '/runs/' + encodeURIComponent(this.run.run_id) + '/clarify', this.pendingClarify)); this.pendingClarify = null; } catch (e) { if (e.responseKnown) this.pendingClarify = null; this.error = e.responseKnown ? e.message : '选择提交结果暂未确认，请重试同一次确认。'; } finally { this.sending = false; } },
    async cancel() { if (!this.active) return; this.cancelling = true; this.progress = '正在取消'; try { this.update(await request('POST', '/runs/' + encodeURIComponent(this.run.run_id) + '/cancel', this.binding(), { keepalive: true })); } catch (_) { this.progress = '暂未确认取消结果，请检查网络。'; this.schedule(); } },
    async download() { if (!this.answer || !this.answer.export) return; this.downloading = true; try { const blob = await request('GET', '/runs/' + encodeURIComponent(this.run.run_id) + '/export', this.binding(), { binary: true }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = this.answer.export.filename || '经营数据.xlsx'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { this.error = e.message || '文件暂不可下载，请重新查询。'; } finally { this.downloading = false; } }
  }
};
</script>
<style scoped>
.trial{margin-top:24px;padding-top:18px;border-top:1px solid #e1e7ef;color:#304861}h3{font-size:16px}p{line-height:1.7}button,select,input{font:inherit}button{padding:8px 12px;border:1px solid #cbd5e1;background:#fff;border-radius:5px;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:10px;margin:12px 0;flex-wrap:wrap}.error{color:#9a3412}.guidance,article{padding:16px;border:1px solid #d8e0eb;border-radius:8px;margin:12px 0}fieldset{border:0;padding:8px 0}.choice{display:block;margin:10px 0}.choice input{margin-right:8px}.cards{display:flex;flex-wrap:wrap;gap:12px}.cards article{min-width:240px}.cards strong{font-size:25px;color:#1f5f8b}details{margin:12px 0}pre{white-space:pre-wrap;word-break:break-word;background:#f6f8fb;padding:12px;max-height:350px;overflow:auto}.table-scroll{overflow:auto}table{border-collapse:collapse}th,td{padding:8px;border:1px solid #e1e7ef}select,input[type=date]{padding:8px;margin:8px;border:1px solid #cbd5e1;border-radius:5px}
</style>
